### ISSUE TITLE
Error: The bucket must be conform to the specifications

### ISSUE THREAD

**Issue by softguy888** [AgoraIO-Usecase/eEducation#102]
Error: The bucket must be conform to the specifications

eval
src/utils/helper.ts:38:6

**Comment by Matrixbirds** [comment]
Our web education demo use OSS bucket to save media resources. Can u provide me the error stack log here.

**Comment by AbdMohamed** [comment]
how get OSS bucket parameters and sdk board token  ?

**Comment by plutoless** [comment]
you will need to prepare your own OSS. for whiteboard token please register your account at https://herewhite.com/en/
