### ISSUE TITLE
Cannot find module '../../build/Release/agora_node_ext', electron demo can not work on my mac os

### ISSUE THREAD

**Issue by braveoyster** [AgoraIO-Usecase/eEducation#107]
hi,
我clone了当前库，配置了相关oss，whiteboard等配置项，web版本在浏览器可以正常运行，但electron无法运行：
1. 无法获得各device选项，console报错信息如下：
![image](https://user-images.githubusercontent.com/4566163/78529571-72dd3480-7814-11ea-92da-a2120645d087.png)

应该是agora sdk依赖导致，这个依赖路径应该是怎么样的，请问具体是什么问题，以及如何解决？请给些指导吧，谢谢。

环境信息如下：
node: v12.6.1 LTS
macOS: 10.15.4 
electron: 5.0.8

**Comment by Matrixbirds** [comment]
找不到这个文件的报错应该是npm install阶段下载插件的过程失败了 正常安装完成应该会有如下的提示

![image](https://user-images.githubusercontent.com/9990676/78809419-7847a400-79f9-11ea-875b-dfcaa17d59dc.png)


如果没有的话 您可以手动访问这个地址 
[http://download.agora.io/sdk/release/Electron-mac-2.9.1-beta.4-5.0.8.zip](http://download.agora.io/sdk/release/Electron-mac-2.9.1-beta.4-5.0.8.zip)

把文件下载好的.zip文件 解压到node_modules/agora-electron-sdk/目录里

![image](https://user-images.githubusercontent.com/9990676/78810053-63b7db80-79fa-11ea-9bed-ba711d68c0c7.png)


这里需要把zip包里的js目录和build目录 放置到
node_modules/agora-electron-sdk/js
node_modules/agora-electron-sdk/build

**Comment by braveoyster** [comment]
awesome!! Thanks a lot, will close this issue.
