### ISSUE TITLE
怎么使小班课程的视频全屏以后切换到720P视频？

### ISSUE THREAD

**Issue by Tranzer168** [AgoraIO-Usecase/eEducation#109]
进入教室默认的是低分辨率状态。如何才能双击全屏以后变成720P

**Comment by plutoless** [comment]
你可以使用
https://docs.agora.io/cn/Video/API%20Reference/web/interfaces/agorartc.client.html#enabledualstream
配合
https://docs.agora.io/cn/Video/API%20Reference/web/interfaces/agorartc.client.html#setremotevideostreamtype
在发送时设置发送为720P，然后接收的时候如果是小屏通过setremotevideostreamtype选择小流，大屏选择大流
