### ISSUE TITLE
x-agora token is required

### ISSUE THREAD

**Issue by klionsome** [AgoraIO-Usecase/eEducation#11]
The app shows the message:

"x-agora token is required"

in strings_configs.xml have been entered:

agora_app_id which is APP IP from Project Management console

agora_auth which is Costumer ID from RESTful API page

The message is still show up

**Comment by srs888001** [comment]
the `agora_auth` needs to be generated like this:
`Base64(Customer ID:Customer Secret)`

**Comment by klionsome** [comment]
Would it be correct this code:

```
<resources>
    <string name="agora_app_id" translatable="false">"<My APP ID>"</string>
    <string name="agora_auth" translatable="false">
        String plainCredentials = "<My Key>:<My Secret>";
        String base64Credentials = new String(Base64.encodeBase64(plainCredentials.getBytes()));
        Request request = new Request.Builder()
        .addHeader("Authorization", "Basic " + base64Credentials);
    </string>
</resources>

```

Still getting this message "x-agora token is required"

**Comment by srs888001** [comment]
I'm not sure whether your `Base64` is generated correctly. Theoretically, Android has its own `Base64` generation method:
`String strBase64 = Base64.encodeToString( plainCredentials.getBytes (), Base64.DEFAULT);`

You can adjust the above method to generate auth. if not, can you upload the log in the page number and provide us with the log serial number. We then look for the problem.

**Comment by TheBossBaby** [comment]
I am also getting same error in web version, I have set the .env.local file variables as `REACT_APP_AGORA_APP_ID`  is set as APP ID from agora console, `REACT_APP_AGORA_CUSTOMER_ID` is set as customer id from agora Rest API console, `REACT_APP_AGORA_CUSTOMER_CERTIFICATE` = App certificate, `REACT_APP_AGORA_RESTFULL_TOKEN` = I generated token using RTM Token generator using this [Documentation](https://docs.agora.io/en/Real-time-Messaging/rtm_token?platform=Android#generate-an-rtm-token)

**Comment by srs888001** [comment]
`REACT_APP_AGORA_RESTFULL_TOKEN` does not need to be filled in now.
I suspect that `REACT_APP_AGORA_CUSTOMER_CERTIFICATE` was filled in incorrectly, how did you get the `App certificate`?

**Comment by TheBossBaby** [comment]
Thanks for quick response, I copied the app certificate from security section of Edit Project.

Okay I will remove the token.

**Comment by srs888001** [comment]
You should also get it from the console from the Rest API console.
