### ISSUE TITLE
ios when techer accept student other student can talk Lecture Hall 

### ISSUE THREAD

**Issue by abufaeys** [AgoraIO-Usecase/eEducation#110]
hi,

problem when teacher accept student other ios students can talk in Lecture Hall , and what we need is one student can talk when teacher accept .

thank you

**Comment by srs888001** [comment]
It looks like a bug..Can you give the operation steps？

**Comment by abufaeys** [comment]
when teacher accept student request, the other users can talk I test it with web teacher  and 2 ios,

or  web teacher  and 1 android and 1 ios, when teacher accept android , ios user can talk .

i test it in agora example .

**Comment by srs888001** [comment]
Thanks for your feedback, we will update a version in the next few days.

**Comment by fadidaoud** [comment]
Hi, i have the same issue , always ios users can talk when teacher accept hand invitations from android or web .

**Comment by srs888001** [comment]
We fixed the issue in the branch：hotfix-iOS-5.1.2
