### ISSUE TITLE
Hi do you have any video tutorial about installation? actually i don't know anything about Node Js. that's why i couldn't run NPM install. 

### ISSUE THREAD

**Issue by edumaenglish** [AgoraIO-Usecase/eEducation#119]
Could you please tell me how to install it on my web hosting? there is any video or tutorial? i followed all steps but still couldn't run NPM install.  i want to create a small classroom for my center. i'm willing to pay you money if you can do it for me or help me to do it. do you have any contact number or app?

**Comment by plutoless** [comment]
you will need to install nodejs first before you can run npm install.

**Comment by edumaenglish** [comment]
actually, i never tried nodejs before. that's why i have no idea. i tried watching some youtube videos. but still don't understand it. may i have your contact number or any app? you can install and customize it for me? i will pay you for that.

**Comment by plutoless** [comment]
please try contacting our sales team. maybe they will introduce you some outsourcing team to help you out.

**Comment by edumaenglish** [comment]
i Emailed them before. no one replies

**Comment by edumaenglish** [comment]
Hi i got an error while installing. can you tell me how to solve it?

npm WARN deprecated chokidar@1.7.0: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated core-js@2.6.11: core-js@

**Comment by Matrixbirds** [comment]
I think this message wouldn't effect in build step. Please show me which u stucked.

**Comment by edumaenglish** [comment]
i even couldn't install it on my hosting. i've uploaded all files and package.json. but when i click run NPM. i got this kind of error message npm WARN deprecated chokidar@1.7.0: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated core-js@2.6.11: core-js@

i've contacted with support team but till now no helpful news. i want to use e-education for my class. can you help me to install it? actually, i have no idea about node.js

**Comment by edumaenglish** [comment]
can you help me to install e-education on my hosting? i will pay for support and installing.

**Comment by edumaenglish** [comment]
can you send me any installing tutorial guide or you install in my hosting, please?

**Comment by plutoless** [comment]
you can ignore the warnings. you will need to follow the guide at https://github.com/AgoraIO-Usecase/eEducation/tree/master/education_web#production-build to create a production build and put on your own hosting.

**Comment by oluudeh** [comment]
> 
> 
> i even couldn't install it on my hosting. i've uploaded all files and package.json. but when i click run NPM. i got this kind of error message npm WARN deprecated chokidar@1.7.0: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
> npm WARN deprecated core-js@2.6.11: core-js@
> 
> i've contacted with support team but till now no helpful news. i want to use e-education for my class. can you help me to install it? actually, i have no idea about node.js

I am having the same issue running npm install on my dev environment. Any progress yet?

**Comment by plutoless** [comment]
@oluudeh sorry what is the error you are having?

**Comment by oluudeh** [comment]
It cannot find white-web-sdk even after I have installed it.

**Comment by srs888001** [comment]
When you run `npm install`, you can ignore all warnings until you find any error. 
Whether there is error information during the installation. If it doesn't mean that your library installation is successful, otherwise, please tell us the error information. 
Then you can run `npm run dev` to see if it can be run locally.
