### ISSUE TITLE
遇到education_web项目中窗口无法关闭的情况??

### ISSUE THREAD

**Issue by coooooookie** [AgoraIO-Usecase/eEducation#12]
开发环境win10
代码按照education_web的说明文档运行,发现窗口无法关闭和最小化,platform-container.tsx中的ipc为undefined,不知道是什么原因导致的?

**Comment by Matrixbirds** [comment]
麻烦提供一下本地开发者日志和以及复现环境

**Comment by coooooookie** [comment]
我发现了,只要反复安装包,人品到位就成功了.
