### ISSUE TITLE
E:/zxdzWorkspace/education_web/src/components/form-input.tsx TypeScript error in E:/zxdzWorkspace/education_web/src/components/form-input.tsx(32,8): Type '{ children: never[]; className: string; value: any; onChange: (evt: any) => void; }' is not assignable to type 'IntrinsicAttributes & InputProps'.   Property 'children' does not exist on type 'IntrinsicAttributes & InputProps'.  TS2322      30 |     <>     31 |       <InputLabel>{props.Label}</InputLabel>   > 32 |       <Input className={classes.formInput} value={props.value}        |        ^     33 |         onChange={onChange}>     34 |       </Input>     35 |       {props.requiredText ? <Typography className={classes.required}>{props.requiredText}</Typography> : null}

### ISSUE THREAD

**Issue by chenbj123** [AgoraIO-Usecase/eEducation#123]
E:/zxdzWorkspace/education_web/src/components/form-input.tsx
TypeScript error in E:/zxdzWorkspace/education_web/src/components/form-input.tsx(32,8):
Type '{ children: never[]; className: string; value: any; onChange: (evt: any) => void; }' is not assignable to type 'IntrinsicAttributes & InputProps'.
  Property 'children' does not exist on type 'IntrinsicAttributes & InputProps'.  TS2322

    30 |     <>
    31 |       <InputLabel>{props.Label}</InputLabel>
  > 32 |       <Input className={classes.formInput} value={props.value}
       |        ^
    33 |         onChange={onChange}>
    34 |       </Input>
    35 |       {props.requiredText ? <Typography className={classes.required}>{props.requiredText}</Typography> : null}

**Comment by Matrixbirds** [comment]
It seems ur matrial-ui dependencies using old type declaration. Pls check it version at least above 4.9.1

**Comment by chenbj123** [comment]
> It seems ur material-ui dependencies using old type declaration. Pls check it version at least above 4.9.1
改成 "@material-ui/core": "^4.9.13",也不行啊

**Comment by Matrixbirds** [comment]
您可以清理一下您这里的包管理缓存 
rm -rf node_modules && npm cache verify
然后再npm install一下
