### ISSUE TITLE
Unable to see video when join as teacher

### ISSUE THREAD

**Issue by Aditya-Bailey** [AgoraIO-Usecase/eEducation#125]

**Comment by plutoless** [comment]
maybe provide a screenshot?

**Comment by edumaenglish** [comment]
![done](https://user-images.githubusercontent.com/64199432/80990071-0465b380-8e60-11ea-8de7-90bf846b75da.png)

**Comment by Aditya-Bailey** [comment]
![Screen Shot 2020-05-04 at 11 25 22 PM](https://user-images.githubusercontent.com/41022713/80997339-c5832e00-8e5e-11ea-86ed-2b045530484f.png)

**Comment by Aditya-Bailey** [comment]
Hi edumaenglish can you help me. I am not getting video.

**Comment by Aditya-Bailey** [comment]
> maybe provide a screenshot?

I have added the screenshot

**Comment by edumaenglish** [comment]
Add me on Skype urkyfight2

**Comment by Aditya-Bailey** [comment]
> Add me on Skype urkyfight2

would you?

**Comment by plutoless** [comment]
@Aditya-Bailey the error is saying you have enabled token feature while not providing it. if you want to quickly start running it you can temporarily disable token feature or simple create a new project under your current account.

**Comment by Aditya-Bailey** [comment]
@plutoless I want to run it using generated rtc and rtm tokens. Although the rtc-rtm tokens , that I am generating and using , are letting me login but I cannot see the video.
Also, I am only able to login when I create rtmToken https://github.com/AgoraIO/Tools/blob/master/DynamicKey/AgoraDynamicKey/nodejs/sample/RtmTokenBuilderSample.js using account I need to modify the code in https://github.com/AgoraIO-Usecase/eEducation/blob/master/education_web/src/stores/room.ts (const { roomType, role, uid, rid, rtmToken } = payload;
    console.log("payload: ", payload);
    let result = { permitted: true, reason: '' };
    await this.rtmClient.login(uid, rtmToken);)  to const { roomType, role, uid,roomName, rid, rtmToken } = payload;
    console.log("payload: ", payload);
    let result = { permitted: true, reason: '' };
    await this.rtmClient.login(roomName, rtmToken);
