### ISSUE TITLE
NO_AUTHORIZED error

### ISSUE THREAD

**Issue by Aditya-Bailey** [AgoraIO-Usecase/eEducation#126]
Agora-SDK [ERROR]: [36F32] Get server node failed [NO_AUTHORIZED] https://webrtc2-ap-web-1.agora.io/api/v1 NO_AUTHORIZED

**Comment by plutoless** [comment]
hi, looks like you have enabled token feature while not providing it when joining channel. if you are not familiar with it, you may create a new project under your account disabling token feature

**Comment by Aditya-Bailey** [comment]
> hi, looks like you have enabled token feature while not providing it when joining channel. if you are not familiar with it, you may create a new project under your account disabling token feature

I am able to login with generated rtm token but not able to see video.
I guess there is some problem with my rtcToken>
```
const appID = process.env.AGORA_APP_ID;
            const appCertificate = process.env.AGORA_APP_CERTIFICATE;
            const channelName = req.params.roomId || 'testUser-1';
            const uid = req.query.userId || 0;
            const account = req.query.userId || 0;
            const rtcRole = RtcRole.PUBLISHER;
            const rtmRole = RtcRole.Rtm_User;
            const expirationTimeInSeconds = 360000

            const currentTimestamp = Math.floor(Date.now() / 1000)
            
            const privilegeExpiredTs = currentTimestamp + expirationTimeInSeconds
            
            // Build rtc-token 
            const tokenA = RtcTokenBuilder.buildTokenWithAccount(appID, appCertificate, channelName, account, rtcRole, privilegeExpiredTs);

            // Build rtm-token 
            const tokenB = RtmTokenBuilder.buildToken(appID, appCertificate, channelName, account, rtmRole, privilegeExpiredTs);
```

**Comment by plutoless** [comment]
@Aditya-Bailey pls check if the channel name the uid matches with the one you use to join channel

**Comment by Aditya-Bailey** [comment]
> @Aditya-Bailey pls check if the channel name the uid matches with the one you use to join channel

I am not using the uid, using account to generate rtcToken. and the channel name is same.
may i know which token to replace here (// WARN: IF YOU ENABLED APP CERTIFICATE, PLEASE SIGN YOUR TOKEN IN YOUR SERVER SIDE AND OBTAIN IT FROM YOUR OWN TRUSTED SERVER API)

**Comment by plutoless** [comment]
you need to read the code and find places where join api is called, try to fetch a token from your own server and then join.
If this is too difficult the suggestion is to create a new project w/o token enabled, could be easier for you to start running the project first.

**Comment by Aditya-Bailey** [comment]
> you need to read the code and find places where join api is called, try to fetch a token from your own server and then join.
> If this is too difficult the suggestion is to create a new project w/o token enabled, could be easier for you to start running the project first.

yes without token , it is fine and working properly. But i need the rtc rtm token from server

**Comment by plutoless** [comment]
then you have to read the code and find the places where we login/join rtc/rtm

**Comment by Aditya-Bailey** [comment]
> then you have to read the code and find the places where we login/join rtc/rtm

yes I did, working now. Thanks for your support.
