### ISSUE TITLE
画笔走位！！

### ISSUE THREAD

**Issue by softmaxs** [AgoraIO-Usecase/eEducation#13]
演示地址：https://solutions.agora.io/education/web/
进入小班房间，点击隐藏学生和消息列表面板的按钮，然后画笔走位了。

**Comment by srs888001** [comment]
谢谢你的反馈， 我们正在处理，处理完成，会在这里更新状态。

**Comment by Matrixbirds** [comment]
@softmaxs 已在修复预览页，没处理dom resizing的场景导致的，可以参考下新[commit](https://github.com/AgoraIO-Usecase/eEducation/commit/842ddd796623e6a9cfb72c33974e8835fd68fd6d)

**Comment by softmaxs** [comment]
@Matrixbirds 明白了
