### ISSUE TITLE
need help in Migrate Agora Web SDK to Agora Web SDK NG

### ISSUE THREAD

**Issue by Aditya-Bailey** [AgoraIO-Usecase/eEducation#137]

**Comment by plutoless** [comment]
we have plans to do this in future release. but for now you will need to do it yourself.

**Comment by Aditya-Bailey** [comment]
> we have plans to do this in future release. but for now you will need to do it yourself.

Ok. could you please let me know how soon would you do the future release.

**Comment by plutoless** [comment]
we can't give you precise date but it's likely Q3
