### ISSUE TITLE
x-agora-token is required

### ISSUE THREAD

**Issue by ecavalier** [AgoraIO-Usecase/eEducation#138]
When I try to login to room return
{message: "x-agora-token is required"}

REACT_APP_AGORA_RESTFULL_TOKEN
I use console to generate temp token but it didn’t work

**Comment by srs888001** [comment]
The generation of `REACT_APP_AGORA_RESTFULL_TOKEN` can refer to  https://github.com/AgoraIO-Usecase/eEducation#pass-the-basic-http-authentication

**Comment by ecavalier** [comment]
> The generation of `REACT_APP_AGORA_RESTFULL_TOKEN` can refer to https://github.com/AgoraIO-Usecase/eEducation#pass-the-basic-http-authentication

I used generated  temp token

**Comment by plutoless** [comment]
@ecavalier that's a different one. please follow the above link to generate your token.

**Comment by ecavalier** [comment]
I generated token using the link above but the error still exists 
when I used postman and pass x-agora-token && x-agora-uid it's success and returns roomId

**Comment by ecavalier** [comment]
It's worked can, thanks

**Comment by lanbaba** [comment]
You need calc base64Credentials and fill into REACT_APP_AGORA_RESTFULL_TOKEN.
Below steps is ok.
First, install base-64
cnpm install base-64
Then calc base64Credentials.
let base64 = require('base-64');
base64.encode(REACT_APP_AGORA_CUSTOMER_ID + ":" + REACT_APP_AGORA_CUSTOMER_CERTIFICATE)
