### ISSUE TITLE
桌面应用白屏？

### ISSUE THREAD

**Issue by softmaxs** [AgoraIO-Usecase/eEducation#14]
环境
win10 64位
vs code
electron 7.1.14
agora-rtc-sdk 3.0.0
agora-rtm-sdk 1.2.2
"agora_electron": {
  "electron_version": "7.1.2",
  "prebuilt": true,
  "platform": "win32"
},

问题描述
代码是克隆gihub上的代码，运行后，ctrl+s保存热加载桌面应用就会白屏，每次都得关闭桌面应用重新运行，开发很慢，这是什么原因导致的？

**Comment by Matrixbirds** [comment]
你是开发electron的部分吗 可以打开electron的log看下日志 demo里目前没有处理hot reload。
```bash
set ELECTRON_ENABLE_LOGGING=1
```

**Comment by softmaxs** [comment]
@Matrixbirds 嗯，使用的electron。
一部分日志内容，没看出有什么错误！！

INFO    18:20:44:942  11796; [rs] **report stats: seq: 20, report list size 0, tx/rx: 2842/960, cache size: 0
INFO    18:20:44:942  11796; [rs] report server1: 114.236.93.137:8913
Local Date: 9月 09 2020 Local Time: 09:32:56
Build info: Jul 14 2020 01:15:07 r

INFO    09:32:56:946   7240; [rs] **report stats: seq: 24, report list size 0, tx/rx: 3293/1152, cache size: 0
INFO    09:32:56:946   7240; [rs] report server1: 150.138.153.21:8913
Local Date: 9月 09 2020 Local Time: 09:37:33
Build info: Jul 14 2020 01:15:07 r

INFO    09:37:33:203   6248; [rs] **report stats: seq: 21, report list size 0, tx/rx: 2940/1008, cache size: 0
INFO    09:37:33:203   6248; [rs] report server1: 119.84.136.54:8913
Local Date: 9月 09 2020 Local Time: 09:44:11
Build info: Jul 14 2020 01:15:07 r

INFO    09:44:11:062   6580; [rs] **report stats: seq: 21, report list size 0, tx/rx: 2940/1008, cache size: 0
INFO    09:44:11:062   6580; [rs] report server1: 14.17.81.121:8913
Local Date: 9月 09 2020 Local Time: 09:51:40
Build info: Jul 14 2020 01:15:07 r

INFO    09:51:40:466   8960; [rs] **report stats: seq: 21, report list size 0, tx/rx: 2940/1008, cache size: 0
INFO    09:51:40:466   8960; [rs] report server1: 182.201.243.7:8913
Local Date: 9月 09 2020 Local Time: 09:59:53
Build info: Jul 14 2020 01:15:07 r

INFO    09:59:53:164   4748; [rs] **report stats: seq: 21, report list size 0, tx/rx: 2940/1008, cache size: 0
INFO    09:59:53:164   4748; [rs] report server1: 150.138.153.21:8000

**Comment by srs888001** [comment]
我们这边没有发现这个问题，你那边是否修改过什么东西？  或者你重新安装下，在测试下？
