### ISSUE TITLE
Login failure, please check your network

### ISSUE THREAD

**Issue by keithwang5** [AgoraIO-Usecase/eEducation#143]
I tried deploying via web locally (http://localhost:3000/#/) and received this error. I followed the setup instructions and wondered if I miss any step or configured something wrongly, please help, thank you.

<img width="536" alt="Screen Shot 2020-05-19 at 10 08 23 PM" src="https://user-images.githubusercontent.com/23715950/82336667-71ab4400-9a1d-11ea-894b-02dc57204c31.png">

**Comment by srs888001** [comment]
pls provide the following error log information

**Comment by keithwang5** [comment]
> pls provide the following error log information

I checked the log in Terminal and could not find any error log. Just dozens of warnings.

**Comment by keithwang5** [comment]
Sorry for the long post. Here are the warnings...

Compiled with warnings.

./src/components/video-player.tsx
  Line 120:6:   React Hook useEffect has missing dependencies: 'preview' and 'streamID'. Either include them or remove the dependency array. Outer scope values like 'AgoraRtcEngine' aren't valid dependencies because mutating them doesn't re-render the component  react-hooks/exhaustive-deps
  Line 124:29:  Unexpected mix of '||' and '&&'                                                                                                                                                                                                                        no-mixed-operators
  Line 124:49:  Unexpected mix of '||' and '&&'                                                                                                                                                                                                                        no-mixed-operators
  Line 140:6:   React Hook useEffect has missing dependencies: 'autoplay', 'id', and 'local'. Either include them or remove the dependency array                                                                                                                       react-hooks/exhaustive-deps
  Line 184:6:   React Hook useEffect has an unnecessary dependency: 'AgoraRtcEngine'. Either exclude it or remove the dependency array. Outer scope values like 'AgoraRtcEngine' aren't valid dependencies because mutating them doesn't re-render the component       react-hooks/exhaustive-deps
  Line 230:6:   React Hook useEffect has an unnecessary dependency: 'AgoraRtcEngine'. Either exclude it or remove the dependency array. Outer scope values like 'AgoraRtcEngine' aren't valid dependencies because mutating them doesn't re-render the component       react-hooks/exhaustive-deps

./src/components/nav.tsx
  Line 158:6:  React Hook useEffect has a missing dependency: 'timer'. Either include it or remove the dependency array     react-hooks/exhaustive-deps
  Line 204:6:  React Hook useEffect has a missing dependency: 'platform'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
  Line 219:6:  React Hook useEffect has a missing dependency: 'timer'. Either include it or remove the dependency array     react-hooks/exhaustive-deps

./src/pages/classroom/index.tsx
  Line 16:10:  'genUUID' is defined but never used                                                                                                                                                                                                              @typescript-eslint/no-unused-vars
  Line 65:6:   React Hook useEffect has a missing dependency: 'history'. Either include it or remove the dependency array                                                                                                                                       react-hooks/exhaustive-deps
  Line 388:6:  React Hook useEffect has missing dependencies: 'classroom', 'isSmallClass', 'location.pathname', 'roomState.appID', 'roomState.course.rid', 'roomState.me.rtcToken', and 'roomState.me.uid'. Either include them or remove the dependency array  react-hooks/exhaustive-deps
  Line 388:7:  React Hook useEffect has a complex expression in the dependency array. Extract it to a separate variable so it can be statically checked                                                                                                         react-hooks/exhaustive-deps

./src/pages/error-page/state.tsx
  Line 16:3:  Useless constructor  @typescript-eslint/no-useless-constructor

./src/pages/replay/agora-replay.tsx
  Line 186:6:  React Hook useEffect has missing dependencies: 'endTime', 'mediaUrl', 'startTime', and 'whiteboardUUID'. Either include them or remove the dependency array  react-hooks/exhaustive-deps
  Line 220:6:  React Hook useEffect has a missing dependency: 'onWindowResize'. Either include it or remove the dependency array                                            react-hooks/exhaustive-deps
  Line 279:6:  React Hook useCallback has missing dependencies: 'handlePlayerClick' and 'playState'. Either include them or remove the dependency array                     react-hooks/exhaustive-deps

./src/pages/replay/replay.tsx
  Line 1:58:   'useState' is defined but never used                                                                                                                                                                                                                  @typescript-eslint/no-unused-vars
  Line 15:10:  'isElectron' is defined but never used                                                                                                                                                                                                                @typescript-eslint/no-unused-vars
  Line 87:6:   React Hook useMemo has an unnecessary dependency: 'replayStore.state'. Either exclude it or remove the dependency array. Outer scope values like 'replayStore.state' aren't valid dependencies because mutating them doesn't re-render the component  react-hooks/exhaustive-deps
  Line 220:6:  React Hook useEffect has missing dependencies: 'duration', 'endTime', 'handleSpaceKey', 'mediaUrl', 'onWindowResize', 'roomId', and 'startTime'. Either include them or remove the dependency array                                                   react-hooks/exhaustive-deps
  Line 244:6:  React Hook useCallback has a missing dependency: 'handlePlayerClick'. Either include it or remove the dependency array                                                                                                                                react-hooks/exhaustive-deps

./src/pages/404.tsx
  Line 24:9:  The href attribute is required for an anchor to be keyboard accessible. Provide a valid, navigable address as the href value. If you cannot provide an href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md  jsx-a11y/anchor-is-valid

./src/utils/types.ts
  Line 25:35:  'stream' was used before it was defined    @typescript-eslint/no-use-before-define
  Line 26:40:  'streamID' was used before it was defined  @typescript-eslint/no-use-before-define
  Line 27:38:  'local' was used before it was defined     @typescript-eslint/no-use-before-define

./src/utils/agora-rtc-client.ts
  Line 338:9:  Expected an error object to be thrown  no-throw-literal
  Line 342:9:  Expected an error object to be thrown  no-throw-literal

./src/stores/whiteboard.ts
  Line 33:21:   Unnecessary escape character: \/                      no-useless-escape
  Line 231:11:  'currentDirIndex' is assigned a value but never used  @typescript-eslint/no-unused-vars
  Line 240:11:  'path' is assigned a value but never used             @typescript-eslint/no-unused-vars

./src/utils/agora-web-player/timeline-scheduler.ts
  Line 33:41:  Expected an error object to be thrown  no-throw-literal

./src/components/volume/speaker.tsx
  Line 35:6:  React Hook useEffect has a missing dependency: 'props'. Either include it or remove the dependency array. However, 'props' will change when *any* prop changes, so the preferred fix is to destructure the 'props' object outside of the useEffect call and refer to those specific props inside useEffect  react-hooks/exhaustive-deps

./src/components/chat/message.tsx
  Line 37:6:  React Hook React.useMemo has a missing dependency: 'roomState.course.rid'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

./src/containers/root-container.tsx
  Line 38:6:   React Hook React.useEffect has a missing dependency: 'store'. Either include it or remove the dependency array                                                                                                                                    react-hooks/exhaustive-deps
  Line 102:6:  React Hook useEffect has a missing dependency: 'history'. Either include it or remove the dependency array                                                                                                                                        react-hooks/exhaustive-deps
  Line 214:6:  React Hook useEffect has a missing dependency: 'history'. Either include it or remove the dependency array. Outer scope values like 'roomStore.state.rtm.joined' aren't valid dependencies because mutating them doesn't re-render the component  react-hooks/exhaustive-deps
  Line 241:6:  React Hook useEffect has missing dependencies: 'errorState', 'globalState', 'roomState', and 'whiteboardState'. Either include them or remove the dependency array                                                                                react-hooks/exhaustive-deps

./src/components/whiteboard/agora/rtm-player.tsx
  Line 38:6:   React Hook useEffect has a missing dependency: 'props'. Either include it or remove the dependency array. However, 'props' will change when *any* prop changes, so the preferred fix is to destructure the 'props' object outside of the useEffect call and refer to those specific props inside useEffect  react-hooks/exhaustive-deps
  Line 88:6:   React Hook useMemo has missing dependencies: 'currentSeekTime', 'props.startTime', 'rtmMessages', and 'state'. Either include them or remove the dependency array                                                                                                                                           react-hooks/exhaustive-deps
  Line 88:7:   React Hook useMemo has a complex expression in the dependency array. Extract it to a separate variable so it can be statically checked                                                                                                                                                                      react-hooks/exhaustive-deps
  Line 118:6:  React Hook useCallback has a missing dependency: 'replayMessages'. Either include it or remove the dependency array                                                                                                                                                                                         react-hooks/exhaustive-deps

./src/hooks/use-chat-text.ts
  Line 44:27:  Unexpected mix of '||' and '&&'  no-mixed-operators
  Line 44:59:  Unexpected mix of '||' and '&&'  no-mixed-operators

./src/pages/replay/model.ts
  Line 4:10:   'useParams' is defined but never used                                                                           @typescript-eslint/no-unused-vars
  Line 4:21:   'useLocation' is defined but never used                                                                         @typescript-eslint/no-unused-vars
  Line 4:34:   'Redirect' is defined but never used                                                                            @typescript-eslint/no-unused-vars
  Line 5:8:    'moment' is defined but never used                                                                              @typescript-eslint/no-unused-vars
  Line 6:10:   'Progress' is defined but never used                                                                            @typescript-eslint/no-unused-vars
  Line 7:10:   'globalStore' is defined but never used                                                                         @typescript-eslint/no-unused-vars
  Line 8:10:   'WhiteboardAPI' is defined but never used                                                                       @typescript-eslint/no-unused-vars
  Line 8:25:   'RTMRestful' is defined but never used                                                                          @typescript-eslint/no-unused-vars
  Line 9:10:   'whiteboard' is defined but never used                                                                          @typescript-eslint/no-unused-vars
  Line 10:10:  'RtmPlayerState' is defined but never used                                                                      @typescript-eslint/no-unused-vars
  Line 28:6:   React Hook React.useEffect has a missing dependency: 'store'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

./src/components/toast.tsx
  Line 4:10:  'isEmpty' is defined but never used                                                                          @typescript-eslint/no-unused-vars
  Line 33:6:  React Hook useEffect has a missing dependency: 'duration'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

./src/stores/room.ts
  Line 526:7:  Expected a 'break' statement before 'case'  no-fallthrough

./src/utils/agora-electron-client.ts
  Line 53:26:   'uid' was used before it was defined            @typescript-eslint/no-use-before-define
  Line 328:13:  'onFailure' is assigned a value but never used  @typescript-eslint/no-unused-vars

./src/hooks/use-streams.ts
  Line 57:6:   React Hook useMemo has missing dependencies: 'course.teacherId' and 'me.uid'. Either include them or remove the dependency array                          react-hooks/exhaustive-deps
  Line 58:5:   React Hook useMemo has a complex expression in the dependency array. Extract it to a separate variable so it can be statically checked                    react-hooks/exhaustive-deps
  Line 131:6:  React Hook useMemo has missing dependencies: 'course.teacherId', 'me.role', 'me.uid', and 'screenId'. Either include them or remove the dependency array  react-hooks/exhaustive-deps
  Line 132:5:  React Hook useMemo has a complex expression in the dependency array. Extract it to a separate variable so it can be statically checked                    react-hooks/exhaustive-deps
  Line 214:6:  React Hook useMemo has an unnecessary dependency: 'me.role'. Either exclude it or remove the dependency array                                             react-hooks/exhaustive-deps

./src/components/mediaboard.tsx
  Line 5:10:    'AgoraStream' is defined but never used                                                                                                                                                                                                                 @typescript-eslint/no-unused-vars
  Line 10:10:   'AgoraElectronClient' is defined but never used                                                                                                                                                                                                         @typescript-eslint/no-unused-vars
  Line 21:10:   'platform' is defined but never used                                                                                                                                                                                                                    @typescript-eslint/no-unused-vars
  Line 25:10:   'Collapse' is defined but never used                                                                                                                                                                                                                    @typescript-eslint/no-unused-vars
  Line 25:20:   'Paper' is defined but never used                                                                                                                                                                                                                       @typescript-eslint/no-unused-vars
  Line 171:6:   React Hook useMemo has missing dependencies: 'location.pathname' and 'me.role'. Either include them or remove the dependency array                                                                                                                      react-hooks/exhaustive-deps
  Line 207:37:  Expected to return a value at the end of arrow function                                                                                                                                                                                                 array-callback-return
  Line 220:6:   React Hook useMemo has missing dependencies: 'items' and 'role'. Either include them or remove the dependency array                                                                                                                                     react-hooks/exhaustive-deps
  Line 322:6:   React Hook useEffect has missing dependencies: 'course.boardId', 'course.boardToken', 'location.pathname', and 'rtmState.joined'. Either include them or remove the dependency array                                                                    react-hooks/exhaustive-deps
  Line 322:7:   React Hook useEffect has a complex expression in the dependency array. Extract it to a separate variable so it can be statically checked                                                                                                                react-hooks/exhaustive-deps
  Line 377:6:   React Hook useCallback has missing dependencies: 'convertPhase' and 'uploadPhase'. Either include them or remove the dependency array                                                                                                                   react-hooks/exhaustive-deps
  Line 437:6:   React Hook useEffect has a missing dependency: 'me.role'. Either include it or remove the dependency array. Outer scope values like 'roomStore.state.course.lockBoard' aren't valid dependencies because mutating them doesn't re-render the component  react-hooks/exhaustive-deps

./src/pages/replay/index.tsx
  Line 5:10:   'Tooltip' is defined but never used               @typescript-eslint/no-unused-vars
  Line 10:8:   'Icon' is defined but never used                  @typescript-eslint/no-unused-vars
  Line 14:10:  'loading' is assigned a value but never used      @typescript-eslint/no-unused-vars
  Line 18:9:   'handleClick' is assigned a value but never used  @typescript-eslint/no-unused-vars

./src/hooks/use-setting-control.tsx
  Line 65:17:  Assignments to the 'mounted' variable from inside React Hook useEffect will be lost after each render. To preserve the value over time, store it in a useRef Hook and keep the mutable value in the '.current' property. Otherwise, you can move this variable directly inside useEffect  react-hooks/exhaustive-deps
  Line 203:6:  React Hook useEffect has a missing dependency: 'platform'. Either include it or remove the dependency array                                                                                                                                                                               react-hooks/exhaustive-deps

./src/utils/api/rtm-restful.ts
  Line 91:7:  Expected an error object to be thrown  no-throw-literal

./src/utils/agora-web-player/agora-player.ts
  Line 94:7:  Expected an error object to be thrown  no-throw-literal
  Line 99:7:  Expected an error object to be thrown  no-throw-literal

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

**Comment by keithwang5** [comment]
Hi @plutoless , I'm sorry but I'm new to web development. 

I ran npm run web and the page did load as shown in the screenshot. But after keying in the room name (generated from the dashboard) and my user name, I'm unable to login. I have a stable internet connection.

Please help.

**Comment by srs888001** [comment]
u need to open the `console`, right-click to save it and give it to us. Or switch to the `network `option, find the wrong request, and give us the details of the wrong request.

**Comment by keithwang5** [comment]
I realised it's because the .env.example file isn't saved properly as .env.local. It was .env.local.example. Thank you.

**Comment by suretrust** [comment]
@keithwang5, could you kindly take a look at my `.env` file? I am having this same issue. https://github.com/Ylurn/agora-test/blob/master/.env
