### ISSUE TITLE
进入房间返回Please setting herewhite token in the Console.

### ISSUE THREAD

**Issue by cwg31825** [AgoraIO-Usecase/eEducation#146]
msg: "Please setting herewhite token in the Console."
code: 1101018

**Comment by MYQ1996** [comment]
能说一下您是怎么解决的吗？

**Comment by plutoless** [comment]
@MYQ1996 需要去声网控制面板设置一些白板的token，这边可以详细阅读一下readme

**Comment by MYQ1996** [comment]
@plutoless 前几天调试的时候也发现了，在项目中设置好token之后，就可以解决这个问题，非常感谢你的回答

**Comment by wshsenanayaka** [comment]
Can have english

**Comment by wshsenanayaka** [comment]
Same Problem -  "Please setting herewhite token in the Console"

**Comment by yoreland** [comment]
You need configure whiteboard token on agora console.
You could find the detailed guideline in project readme.

**Comment by wshsenanayaka** [comment]
I Created the netless Account  and get SDK-Token
After I put that Token here --

![Screen Shot 2020-06-09 at 4 02 50 PM](https://user-images.githubusercontent.com/32666359/84137755-be0d0100-aa6a-11ea-8200-4f27aa840306.png)

**Comment by wshsenanayaka** [comment]
# agora http basic authorization
  REACT_APP_AGORA_RESTFULL_TOKEN=agora_restful_api_token 

agora_restful_api_token ---- ???

**Comment by yoreland** [comment]
> # agora http basic authorization
> REACT_APP_AGORA_RESTFULL_TOKEN=agora_restful_api_token
> 
> agora_restful_api_token ---- ???

You need use customer_id and customer_token to generate a base64 token.
Some thing like: 
REACT_APP_AGORA_RESTFULL_TOKEN="MzgzMzM3***NGNhZTQ="

**Comment by wshsenanayaka** [comment]
How i can generate  -- 
You need use customer_id and customer_token to generate a base64 token.

My 
REACT_APP_AGORA_CUSTOMER_ID=5bda1feadbb445d5b03e66763dbc6b3e
REACT_APP_AGORA_CUSTOMER_CERTIFICATE=bebfb97e7bb942da8ae031fb96a8141f

**Comment by yoreland** [comment]
there is the link for this guideline
https://docs.agora.io/en/faq/restful_authentication
if you have trouble to generate base64 ecode string. There should be some online tools on internet as it is a very common function.

**Comment by wshsenanayaka** [comment]
I try it can you help me to generate base64 ecode string

My
REACT_APP_AGORA_CUSTOMER_ID=5bda1feadbb445d5b03e66763dbc6b3e
REACT_APP_AGORA_CUSTOMER_CERTIFICATE=bebfb97e7bb942da8ae031fb96a8141f

**Comment by yoreland** [comment]
please try
REACT_APP_AGORA_RESTFULL_TOKEN="NWJkYTFmZWFkYmI0NDVkNWIwM2U2Njc2M2RiYzZiM2U6YmViZmI5N2U3YmI5NDJkYThhZTAzMWZiOTZhODE0MWY="

**Comment by wshsenanayaka** [comment]
I trt it but same error ...

**Comment by wshsenanayaka** [comment]
![Screen Shot 2020-06-09 at 5 15 52 PM](https://user-images.githubusercontent.com/32666359/84143964-134e1000-aa75-11ea-8d23-1a3dd616e685.png)

**Comment by wshsenanayaka** [comment]
Same Problem - "Please setting herewhite token in the Console"

**Comment by wshsenanayaka** [comment]
What is herewhite token  in Console ??? 
How to generate

**Comment by yoreland** [comment]
herewhite equals nettles.
So can you double check the nettles token has been correctly configured ?

**Comment by wshsenanayaka** [comment]
how to nettles token has been correctly config

**Comment by wshsenanayaka** [comment]
I got the SDK-Token form console netless

**Comment by wshsenanayaka** [comment]
https://github.com/wshsenanayaka/agora-edu.git

**Comment by tuanna2** [comment]
You can fix this problem by removing the ! after Basic ${AUTHORIZATION
in /src/services/edu-api.ts in function AgoraFetchJson

**Comment by Nondukishor** [comment]
> https://github.com/wshsenanayaka/agora-edu.git

Have you solved this problem?

**Comment by gauravthebest** [comment]
@Nondukishor I have solved the issue.
First of all, you need to create 2 accounts, 1st on agora and 2nd on netless.
**Step1:** Get APP_ID, CUSTOMER_ID, and CUSTOMER_CERTIFICATE from the Agora Console.
**Step2:** Create a Base64 encoded string of (CUSTOMER_ID:CUSTOMER_CERTIFICATE), it's a normal base64 encoded string you can easily convert a string to a bast64 on google.
`REACT_APP_AGORA_RESTFULL_TOKEN=Base64(CUSTOMER_ID:CUSTOMER_CERTIFICATE)`
**Step3:** Create a netless whiteboard token and add it to the Agora Console.
I was missing step3, and I  guess others were not creating the right base64 token. Hope this will help you.
