### ISSUE TITLE
Agora-SDK [ERROR]: [8CA10] Get server node failed [DYNAMIC_KEY_EXPIRED]

### ISSUE THREAD

**Issue by hardiktechnource** [AgoraIO-Usecase/eEducation#149]
Hello there,

I have setup Agora education setup node and then added required thing in .env file as 
REACT_APP_AGORA_APP_ID=XXXXXXXXXXXXXXX
REACT_APP_AGORA_APP_TOKEN=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
REACT_APP_AGORA_LOG=true

But when I click on start live broadcast button it shows me error in console says,
Agora-SDK [ERROR]: [8CA10] Get server node failed [DYNAMIC_KEY_EXPIRED]

Not sure what to do next please suggest added screenshot. Any help will be appreciated
![Screenshot 2020-05-28 at 10 58 59 PM](https://user-images.githubusercontent.com/66084535/83174784-83d16480-a138-11ea-98c9-bb27c2fbb258.png)
 
Thanks

**Comment by plutoless** [comment]
the token you used is expired.
