### ISSUE TITLE
how can i get the channel name of the class

### ISSUE THREAD

**Issue by sumitdas4u** [AgoraIO-Usecase/eEducation#15]
i want to record individual feed of teacher and student in cloud recording how to get the channel name ?

**Comment by srs888001** [comment]
Channel name is generated by the `
Agora Edu Cloud Service`. 
You can find the corresponding network request return according to the screenshot below. Or directly in the console, print `roomStore.rtcClient.channel` can also be obtained.

![image](https://user-images.githubusercontent.com/5343094/93036997-ea40ab00-f673-11ea-8617-2ae943b814bb.png)
