### ISSUE TITLE
CORS errors in education_web demo 

### ISSUE THREAD

**Issue by iNishant** [AgoraIO-Usecase/eEducation#150]
Unable to make API requests to the Agora endpoint `https://api.agora.io/dev` because of CORS errors.

![Screenshot 2020-06-02 at 8 33 13 PM](https://user-images.githubusercontent.com/10304344/83536189-8523d800-a510-11ea-87bb-b6c0ca9069e0.png)

Setting `mode: 'no-cors'` in fetch won't work as it will remove the Authorization header needed for the requests.

**Comment by Matrixbirds** [comment]
Can u give me a test link to reproduce your issue

**Comment by iNishant** [comment]
@Matrixbirds this is the repo https://github.com/Ylurn/agora-test

**Comment by iNishant** [comment]
@Matrixbirds deployed the repo here https://agora-test-elyojxfit.now.sh

**Comment by Matrixbirds** [comment]
You need use https://api.agora.io/edu this as prefix url
