### ISSUE TITLE
Ubuntu下遇到的问题，Web项目下，运行npm install后

### ISSUE THREAD

**Issue by llinzzi** [AgoraIO-Usecase/eEducation#154]
> agora-electron-sdk@2.9.0-rc.104-build.509 install /mnt/e/code/eEducation/education_web/node_modules/agora-electron-sdk
> just install

just install

Options:
  --help              Show help                                        [boolean]
  --version           Show version number                              [boolean]
  --config            path to a just-task.js file (includes the file name)
  --electron_version                                          [default: "5.0.8"]
  --runtime                  [choices: "electron", "node"] [default: "electron"]
  --platform                     [choices: "darwin", "win32"] [default: "linux"]
  --debug                                             [boolean] [default: false]
  --silent                                            [boolean] [default: false]
  --msvs_version                                               [default: "2015"]
  --liburl_win                                                     [default: ""]
  --liburl_mac                                                     [default: ""]

Invalid values:
  Argument: platform, Given: "linux", Choices: "darwin", "win32"
[12:50:32 PM] x Error previously detected. See above for error messages.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.7 (node_modules/react-scripts/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/watchpack/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN notsup Unsupported engine for pkcs7@1.0.2: wanted: {"npm":"^1.4.6","node":"^0.10"} (current: {"node":"10.19.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: pkcs7@1.0.2

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! agora-electron-sdk@2.9.0-rc.104-build.509 install: `just install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the agora-electron-sdk@2.9.0-rc.104-build.509 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-06T04_50_34_886Z-debug.log

**Comment by yoreland** [comment]
请确认在web目录下面执行的是否是npm install还是npm just install? 
另外如果是在中国大陆，可以尝试为npm配置镜像代理之后在执行npm install

**Comment by plutoless** [comment]
@llinzzi 这个是因为现在的教育项目包含了electron和web的版本，electron版本目前不支持在ubuntu下安装，如果你只需要web，可以在package.json里把agora-electron-sdk依赖去掉

**Comment by llinzzi** [comment]
> 请确认在web目录下面执行的是否是npm install还是npm just install? 
> 
> 另外如果是在中国大陆，可以尝试为npm配置镜像代理之后在执行npm install

谢谢回复，npm install后，会自动进入 just install环节，然后出错

**Comment by llinzzi** [comment]
> @llinzzi 这个是因为现在的教育项目包含了electron和web的版本，electron版本目前不支持在ubuntu下安装，如果你只需要web，可以在package.json里把agora-electron-sdk依赖去掉

收到，我试试

**Comment by llinzzi** [comment]
> @llinzzi 这个是因为现在的教育项目包含了electron和web的版本，electron版本目前不支持在ubuntu下安装，如果你只需要web，可以在package.json里把agora-electron-sdk依赖去掉

多谢，这个方法问题解决
