### ISSUE TITLE
ReferenceError: self is not defined

### ISSUE THREAD

**Issue by iNishant** [AgoraIO-Usecase/eEducation#163]
I have a next.js ts setup instead of the given CRA. I can run the project locally successfully but when I build the project it throws this error

```
ReferenceError: self is not defined
    at /Users/nishantsingh/Desktop/Ylurn/frontend/website/node_modules/agora-rtm-sdk/index.js:7:61942
    at /Users/nishantsingh/Desktop/Ylurn/frontend/website/node_modules/agora-rtm-sdk/index.js:7:84
    at Object.<anonymous> (/Users/nishantsingh/Desktop/Ylurn/frontend/website/node_modules/agora-rtm-sdk/index.js:7:161)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
```

**Comment by Matrixbirds** [comment]
It seems your next.js scaffold didn‘t configure the web worker compile environment.
In web demo, we are using web worker access Indexeddb to save the application’s log. If you don’t need it, you can directly remove the LogUploader folder

**Comment by iNishant** [comment]
@Matrixbirds https://github.com/Ylurn/agora-web-nextjs you can use this. The local setup works but the build for prod is failing.

**Comment by Matrixbirds** [comment]
> @Matrixbirds https://github.com/Ylurn/agora-web-nextjs you can use this. The local setup works but the build for prod is failing. I am also forcing lazy loading so that no code is loaded on server side.

Our RTM web SDK only support `client-side-rendering` solution with AMD module.

Maybe you need can try to using `script` tag to import RTM SDK in window object your web app.

**Comment by iNishant** [comment]
Yup solved it by lazyloading. Somehow the originally lazyloaded component was being built on the server during next.js 's static optimisation
