### ISSUE TITLE
S3 instead of Alibaba Cloud Object Storage Service

### ISSUE THREAD

**Issue by suretrust** [AgoraIO-Usecase/eEducation#165]
Would it be possible to use S3 instead of Alibaba Cloud Object Storage Service for the OSS configurations in the image below?

<img width="918" alt="Screenshot 2020-06-29 at 15 33 53" src="https://user-images.githubusercontent.com/31304943/86020525-ed86ac00-ba1f-11ea-8841-d06bb815f33b.png">

**Comment by srs888001** [comment]
I'm sorry. Currently, whiteboard only supports  the Object Storage Service (OSS) of Alibaba Cloud and Qiniu Cloud.

**Comment by suretrust** [comment]
Thanks so much for your response, @srs888001! 🙌
