### ISSUE TITLE
Files uploaded not showing on whiteboard

### ISSUE THREAD

**Issue by suretrust** [AgoraIO-Usecase/eEducation#166]
#### After following the instructions [here](https://github.com/AgoraIO-Usecase/eEducation/issues/118) to add my OSS details, I am having 2 issues.

1. Files uploaded to whiteboard are not showing properly, it is displaying as the image below. Those rectangles are actually images uploaded.

<img width="1161" alt="Screenshot 2020-06-29 at 18 03 29" src="https://user-images.githubusercontent.com/31304943/86034720-0cdb0480-ba33-11ea-908d-29b3639030ae.png">

2. When I tried to record I am getting an error as in the image attached below:

<img width="382" alt="Screenshot 2020-06-29 at 18 06 28" src="https://user-images.githubusercontent.com/31304943/86034872-4744a180-ba33-11ea-8252-e8527766cd1e.png">

Could anyone kindly point me in the right direction?

**Comment by srs888001** [comment]
1. Is there any error message? Are all pictures not displayed properly? Can you provide us with a picture?
2. It seems that you have not turned on cloud recording. Maybe you can refer to `https://docs.agora.io/en/cloud-recording/cloud_recording_rest?platform=All%20Platforms#enable-cloud-recording`

**Comment by suretrust** [comment]
#### Thanks for your response @srs888001, 💯 

1. There are some errors in the console, please see the image attached.

<img width="455" alt="Screenshot 2020-06-30 at 04 21 26" src="https://user-images.githubusercontent.com/31304943/86080223-4d19a180-ba8a-11ea-881c-822e46adc70d.png">

2. Thanks so much, now recording, one more thing though, I checked the Alibaba bucket folder and didn't find any recording, how do I locate the recording or play it?

**Comment by Matrixbirds** [comment]
**For question 1.** It looks like OSS network error, you can find more details here. [Network-Error](https://github.com/AlibabaCloudDocs/oss/blob/master/intl.en-US/Errors%20and%20Troubleshooting/Network%20connection%20timeout%20handling.md)  
**For question 2.** Our education service not support record to specified OSS storage, If you need recording service, we recommend to use your own service and integrate the agora cloud recording the into your backend server. You can find agora recording services [documentation](https://docs.agora.io/en/cloud-recording/cloud_recording_api_rest?platform=All%20Platforms).

**Comment by suretrust** [comment]
Thanks for the response @Matrixbirds, 👋 

I just checked the [network-error](https://github.com/AlibabaCloudDocs/oss/blob/master/intl.en-US/Errors%20and%20Troubleshooting/Network%20connection%20timeout%20handling.md) suggestions and they are all already in the code since I'm using the code [here](https://github.com/AgoraIO-Usecase/eEducation/blob/master/education_web/src/utils/upload-manager.ts)

**Comment by suretrust** [comment]
Hi @srs888001 and @Matrixbirds, 👋 

Thanks so much for helping me with this. I finally got it to work, it was partly because I didn't set the Exposed Headers as shown in the image below:

<img width="641" alt="Screenshot 2020-07-01 at 10 09 27" src="https://user-images.githubusercontent.com/31304943/86226081-0cea1a00-bb83-11ea-91df-d3141ea9ffec.png">

**One more question though, when I upload a file that's not image, there is this conversion that fails with 403 error, could you point me in the right direction?**

<img width="710" alt="Screenshot 2020-07-01 at 10 12 11" src="https://user-images.githubusercontent.com/31304943/86226336-6baf9380-bb83-11ea-9029-31df1c289e67.png">

**Comment by suretrust** [comment]
Figured it out, it was because the services listed in the image below were disabled. Thanks, guys, you rock!

<img width="701" alt="Screenshot 2020-07-01 at 15 01 06" src="https://user-images.githubusercontent.com/31304943/86252986-cf4db700-bbab-11ea-816f-e61fff3d801e.png">
