### ISSUE TITLE
有eEducation server 端的demo吗？

### ISSUE THREAD

**Issue by janreyho** [AgoraIO-Usecase/eEducation#167]
”声网为后端开发能力不够的开发者提供 Agora Edu 云服务，实现教室、老师和学生的状态管理以及状态变更的 RTM 频道消息通知，具体功。。。“

如果没有的话，Agora Edu 云服务怎么开启，和使用。相关文档不够清楚呀。

**Comment by srs888001** [comment]
我们目前的代码就是基于Agora Edu 云服务使用的，正常情况下你不需要了解我们Agora Edu 云服务具体是如何实现的，你只需要基于我们目前的代码基础上开发就可以了。
如果你想具体了解Agora Edu 云服务在我们项目中是如何通信的，你可以参考：`https://docs.agora.io/cn/Interactive%20Broadcast/small_classroom_overview?platform=All%20Platforms`

**Comment by janreyho** [comment]
那Agora Edu 云服务是免费试用的吗？[计费说明](https://docs.agora.io/cn/Interactive%20Broadcast/billing_rtc?platform=All%20Platforms#%E8%B4%B9%E7%94%A8%E7%BB%84%E6%88%90)中没有看到相关报价。

**Comment by srs888001** [comment]
Agora Edu 云服务内的功能正常使用是免费的

**Comment by janreyho** [comment]
我们计划自己开发，后端服务。但是不知道应该基于哪些API来开发。

看到Agora Edu 云服务，对外提供的api应该是[education_web](https://github.com/AgoraIO-Usecase/eEducation/blob/master/education_web/src/services/edu-api.ts)吧？

Agora Edu 云服务，应该所依赖声网底层音视频的服务api，在哪里？是[服务端api](https://docs.agora.io/cn/Interactive%20Broadcast/rtc_restful_api?platform=All%20Platforms)？

**Comment by srs888001** [comment]
看到Agora Edu 云服务，对外提供的api应该是education_web吧？
---------------------
是的

Agora Edu 云服务，应该所依赖声网底层音视频的服务api，在哪里？是服务端api？
---------------------
Agora Edu 云服务包含了数据业务和持久化 以及 消息通知。
数据这块不依赖于音视频服务，只有消息通知是基于RTM：`https://docs.agora.io/cn/Real-time-Messaging/rtm_get_event?platform=All%20Platforms`.
一般情况下，我们建议你基于该demo基础上开发，可以为你减少很多不必要的麻烦。

**Comment by janreyho** [comment]
那就是说，我们开发后端服务，起步可以基于**Agora Edu 云服务**，等业务上线比较稳定后。

可以进一步，直接调用音视频、实时消息、白板服务，逐步直至完全代替**Agora Edu 云服务**。

我理解的没有问题吧？

**Comment by plutoless** [comment]
@janreyho 看您的需求，如果您这边有比较完备的能力可以把整套教育系统搭起来，您完全可以不依赖我们的教育云服务而选择直接使用我们的音视频/实时消息和白板SDK来自己从0开始搭，当然您还是可以把我们的教育方案作为一个参考
如果您希望短时间内比较快能把整套教育系统搭起来，或者觉得自己把整个服务搭起来比较难，可以直接用我们提供的教育云服务，他帮您解决了教育方案的整体骨架，提供了一些降低您搭建整套系统难度的一些服务，您可以之后慢慢把里面一些服务修改成你们自己的服务

**Comment by janreyho** [comment]
@plutoless 明白，非常感谢
