### ISSUE TITLE
course recording not opening (web->linux)

### ISSUE THREAD

**Issue by codebluster** [AgoraIO-Usecase/eEducation#17]
course recording doesn't open on local 
it is stuck on Finished preloader

Please suggest what i a can do to fix it

**Comment by srs888001** [comment]
can you describe in detail the problem you are facing now? 
for example, what interface is called and what error message is there.

**Comment by codebluster** [comment]
i am implement cloud classes (lecture hall) from the demo provided on your website and as the classes are in progress i started cloud recording but after stopping the cloud recording the course recording link is provided in the chat
![Screenshot_2020-09-16 Class](https://user-images.githubusercontent.com/70195731/93304342-7ee50d80-f81a-11ea-9b5d-c967afecba7a.png)
 section of the class panel and on click it redirects to another tab where the recorded (whiteboard and teacher audio,video) is to be displayed on that particular interface the video is not played and the screen is stuck with a preloader Finished.
-PFA

**Comment by srs888001** [comment]
This step involves background coding, streaming and other operations. Have you waited for a long time without playing normally?

If you wait for a long time and do not play normally, please provide a log.

**Comment by jackzro** [comment]
i have a same problem ... i dont understand what do you mean about provide a log  can you explain it or you can suggest other solution ??

**Comment by srs888001** [comment]
Enter the developer mode of the web page. There is console output. Here is the log. You can right-click to save it to us. We need to look at the log to see what the problem is.

**Comment by jackzro** [comment]
i cannot find log in console tab 
<img width="1440" alt="Screen Shot 2020-09-24 at 18 33 21" src="https://user-images.githubusercontent.com/36666349/94139842-85b3f600-fe94-11ea-8772-46096b66196b.png">


maybe do you mean this ???
<img width="1440" alt="Screen Shot 2020-09-24 at 18 33 00" src="https://user-images.githubusercontent.com/36666349/94139890-97959900-fe94-11ea-9583-35753d4a6a02.png">

**Comment by jackzro** [comment]
i need to fill this REACT_APP_AGORA_RTM_ENDPOINT  on .env ???
if yes can you tell me example to fill this endpoint ??

**Comment by Matrixbirds** [comment]
Pls paste your log info here, i will check ASAP. @jackzro

**Comment by jackzro** [comment]
20200929053135948 i got from upload log button , is it what do you mean ?

**Comment by Matrixbirds** [comment]
You can provide the console log directly from devtools console here.

**Comment by Matrixbirds** [comment]
@jackzro  I've already checked the log, I found the the recording state changed below,
```js
ChannelMessage cmd:  [object Object]7{"recordId":"106469335601512448","roomId":"106340264200642560","isRecording":1,"recordingTime":1600954533818}
ChannelMessage cmd:  [object Object]7{"recordId":"0","roomId":"106981890925264896","isRecording":0}
```
It seems the Chat component didn't show the `course recording`, You can check with `recording` in project.

**Comment by jackzro** [comment]
in chat component after i stop my recording , in chat component i got course recording and when i open it , the recording didn't show up

**Comment by Matrixbirds** [comment]
You can check [here](https://github.com/AgoraIO-Usecase/eEducation/blob/06dae5d450705dbcf12708e402a2d879b427f3f0/education_web/src/components/chat/message.tsx#L30), add console.log into this hooks. @jackzro

**Comment by jackzro** [comment]
@Matrixbirds i have already  console.log and the output of event method change the value https://github.com/AgoraIO-Usecase/eEducation/blob/06dae5d450705dbcf12708e402a2d879b427f3f0/education_web/src/containers/root-container.tsx#L213 because of this it change the value from {"recordId":"106469335601512448","roomId":"106340264200642560","isRecording":1,"recordingTime":1600954533818} to {"recordId":"0","roomId":"106981890925264896","isRecording":0}, i think we need to check the value of recordId if 0 no need to change ???

**Comment by plutoless** [comment]
@jackzro sorry for late response. we will take a look and come back to you later today.

**Comment by plutoless** [comment]
@jackzro sorry for late reply. the reason is you will need to register backend callback in your console service. this is not yet open to public. is there any chance you can contact our sales team so that they can turn it on for you?

**Comment by lemonheadhs** [comment]
Hi, I setup your demo and also can not get recording to work. Do I need some extra configuration, is it documented somewhere? Can you elaborate more on "register backend callback" stuff?

**Comment by srs888001** [comment]
After the recording and transcoding of version 5.X is successful, the recording service will tell the background a status callback. This configuration needs to be activated by contacting our sales team.
The latest 6.X has an optional requirement to enable this configuration, in the master branch, but we still recommend that you config it.
