### ISSUE TITLE
education_web正常运行起来后上传图片不显示，npm run build 打包后index.html为空白文件

### ISSUE THREAD

**Issue by NeoChen-GitHub** [AgoraIO-Usecase/eEducation#171]
您好，我npm run dev能够正常运行，所有功能都可以实现，但是白板上上传图片、ppt等文件时无法显示，请问是什么原因造成的？另外文件修改homepage为‘./’后打包，生成的build文件夹内index.html打开能显示标题，但内容是空白的

**Comment by CigaLi** [comment]
您好，想请问您在运行npm run dev时遇到过“登陆失败，请检查网络设置”的错误吗，网页内容都能够正常显示。谢谢

**Comment by NeoChen-GitHub** [comment]
感谢回复，我用visual studio code终端运行的程序，过程中没有遇到任何错误。修改了APPID，customerid，customer_certificate，restful_token，项目里面加入了白板token，后面也正确配置了oss，所有功能基本都能实现，但就是上传图片，文件等失败，再就是打包后的build文件双击打开是空白的。但这个build包放到tomcat下是能正常运行显示的。

**Comment by CigaLi** [comment]
非常感谢您的回答，请问`REACT_APP_AGORA_RESTFULL_TOKEN`就是将`REACT_APP_AGORA_CUSTOMER_ID:REACT_APP_AGORA_CUSTOMER_CERTIFICATE`内容用Base64算法编码后的结果吗？
我这样做了，但是还是有登陆失败错误。
我再看看是不是oss配置错误，非常感谢您！

**Comment by NeoChen-GitHub** [comment]
是的，也是直接用base64转的。我觉得跟oss没关系吧，我没配置OSS的时候，也是可以正常运行的，没有登陆错误的提示。

**Comment by srs888001** [comment]
请再次查看我们的什么文档：`https://github.com/AgoraIO-Usecase/eEducation/tree/master/education_web`
当你需要在白板上上传课件的时候才需要配置OSS，否则不需要

**Comment by NeoChen-GitHub** [comment]
您好，我就是在使用上传图片，PPT, 文档等文件时，无法正常上传，显示不出来上传的文件。OSS我在env.local里配置了，但仍然不成功

**Comment by srs888001** [comment]
有错误信息吗

**Comment by NeoChen-GitHub** [comment]
没有任何错误信息。

发自我的iPhone

**Comment by srs888001** [comment]
我们demo界面有个上传日志按钮，（右上方），你可以上传下你的日志，告诉我们你上传日志的序列号，我们来查看下问题

**Comment by NeoChen-GitHub** [comment]
好的，日志ID：20200712134001788

**Comment by srs888001** [comment]
目前除了配置oss外，有没有修改其他东西？  
另外你可以 清楚下缓存：remove node_modules/.cache，然后再测试下。

**Comment by NeoChen-GitHub** [comment]
没有修改过，上传图片时浏览器console报错：aliyun-oss-sdk.js:21469 POST http://your_oss_bucket_name.your_cdn_accelerate_endpoint/e126f3a6-f552-4e0d-927b-91738f3ccb1d%E6%8D%95%E8%8E%B7.PNG?uploads= net::ERR_NAME_NOT_RESOLVED
我问了阿里云工程师，除了没有开启加速所以没有填写外，其他都正确填写了，但是我的bucket名等信息配置代码没能实际生效

**Comment by srs888001** [comment]
看上面请求，你your_oss_bucket_name和your_cdn_accelerate_endpoint根本没有配置啊。  所以你确定你是按照集成文档来配置了吗？

**Comment by NeoChen-GitHub** [comment]
我bucket name真的配置了，而且没问题。但我accelerate-endpoint确实没配置。因为之前问的这个不是必须的。你们的教程里也没说要配置这个
https://gitee.com/anticookies/eEducation/issues/I1EIJZ 
发自我的iPhone

**Comment by srs888001** [comment]
好的，那目前配置了accelerate-endpoint，还有问题吗

**Comment by NeoChen-GitHub** [comment]
嗯嗯，没问题了。原因出在oss里面需要授权设置，目前可以了。非常感谢。
