### ISSUE TITLE
运行npm run dev本地测试时显示登陆失败

### ISSUE THREAD

**Issue by CigaLi** [AgoraIO-Usecase/eEducation#172]
命令启动后的log，不知道哪里出现了错误，求好心人指点一下
----------------------

- log开头

"D:\IDEA\IntelliJ IDEA 2018.1.3\bin\runnerw.exe" E:\nodejs\node.exe E:\nodejs\node_modules\npm\bin\npm-cli.js run dev --scripts-prepend-node-path=auto

> Agora-Edu-Web@5.4.0 dev D:\IDEA-Workspace\eEducation-master\eEducation-master\education_web
> cross-env TSC_COMPILE_ON_ERROR=false REACT_APP_RUNTIME_PLATFORM=web react-app-rewired start

Webpack: Starting ...
The following changes are being made to your tsconfig.json file:
  - compilerOptions.paths must not be set (aliased imports are not supported)

undefined
Starting the development server...

-------------------------------------

- log最后部分

Webpack: Starting ...

  √ Compile modules
  √ Build modules
  √ Optimize modules
  √ Emit files

Webpack: Finished after 89.781 seconds.

Files successfully emitted, waiting for typecheck results...

**Comment by srs888001** [comment]
你有修改任何代码吗？

**Comment by CigaLi** [comment]
> 你有修改任何代码吗？

没有修改代码，就修改了配置文件，我昨天试了很久一直没成功。
今天把整个项目删除，然后重新按照教程弄了一遍，本地终于成功了。（也许是之前不小心弄错了吧）
