### ISSUE TITLE
Internal Server Error | Code 500 

### ISSUE THREAD

**Issue by projovi** [AgoraIO-Usecase/eEducation#175]
I have been trying to use the API, but keep landing on ERROR 500
What am I missing ????

https://api.agora.io/edu/v1/apps/MYAPPID/room/entry?appId=MYAPPID&roomName=12365214231546985&roomUuid=12365214231546985&userName=demouser&userUuid=300000000&role=2&type=2

**Comment by srs888001** [comment]
https://github.com/AgoraIO-Usecase/eEducation/issues/138

**Comment by projovi** [comment]
@srs888001 Thanks,
But it's not the token error.

I have already Included **Authorization** in the header .

Content-Type : application/json

Authorization : Basic MmJkMzk3Y2Q1ZGYwNGM0MDkwMmI0ZmM0NTMwODU1NmE6ZGZh***************************

https://api.agora.io/edu/v1/apps/MYAPPID/room/entry?appId=MYAPPID&roomName=12365214231546985&roomUuid=12365214231546985&userName=demouser&userUuid=300000000&role=2&type=2

---Run In POSTMAN --
{
    "msg": "Internal Server Error",
    "code": 500
}

**Comment by srs888001** [comment]
The API is a post request：`https://api.agora.io/edu/v1/apps/MYAPPID/room/entry`, you can check it again.

**Comment by projovi** [comment]
@srs888001 

I am using post request. Tried it again no luck !

**Comment by srs888001** [comment]
It seems that you still use the RESTFul interface incorrectly. The parameters of the RESTFul interface post request are not directly spliced after the URL, but are put in the body.

**Comment by projovi** [comment]
Attached the REQUEST.

[https://prnt.sc/tqj3zh](url)
[https://prnt.sc/tqj4au](url)

I am using POSTMAN to send requests.

**Comment by srs888001** [comment]
the request body needs to use `JSON`, not `form-data`

**Comment by projovi** [comment]
Worked ! Thanks
