### ISSUE TITLE
Web Screen Sharing will stop after some time

### ISSUE THREAD

**Issue by alexwenbj** [AgoraIO-Usecase/eEducation#176]
On Mac OS + Firefox/Chrome as the host broadcasting to other clients, after 20 or more minutes, the screen sharing will stop automatically, and I have to re-share the screen.

**Comment by srs888001** [comment]
Can you provide the browser version number? 
In addition, can you upload the log and tell us the serial number of the uploaded log.

**Comment by alexwenbj** [comment]
Chrome 83.0.4103.116(64-bit)/Firefox 78.0.2 (64-bit)

**Comment by alexwenbj** [comment]
Maybe it is my fault.It is OK now.
