### ISSUE TITLE
Keep the client video size ratio same as the broadcasting side video size.

### ISSUE THREAD

**Issue by alexwenbj** [AgoraIO-Usecase/eEducation#179]
When launch screen sharing to client, the receiving client video size ratio is different from the broadcasting side original video size, how can I make the client size video size ratio same as the broadcasting side's?
Thank you.

Broadcasting side video ratio:
![image](https://user-images.githubusercontent.com/12047524/88477760-4725bc00-cf75-11ea-90ed-279e7693a910.png)

Client side video ration:
![image](https://user-images.githubusercontent.com/12047524/88477779-63c1f400-cf75-11ea-888a-8d3f06306727.png)

**Comment by srs888001** [comment]
It looks like you need to set the video resolution:`https://docs.agora.io/en/Video/video_profile_web?platform=Web`

**Comment by alexwenbj** [comment]
Is this configure only for the broadcasting side(local stream)? I set up the Screen Profile via setScreenProfile() (cause I used the screen sharing stream) for the local stream, but it not worked.

**Comment by plutoless** [comment]
setScreenProfile is for screenshare. you will need to use setVideoProfile or setVideoEncoderConfiguration for camera.

**Comment by alexwenbj** [comment]
What I need is the share screen video ratio in the client side. @plutoless

**Comment by alexwenbj** [comment]
I ran this demo, and it keep the same ratio for both broadcasting side and client side. But I can't find which configure make it do that.

**Comment by srs888001** [comment]
In demo, we use the CSS property `object-fit: contain!important;` to control the client display. 
However, there is a compatibility problem with this property. You need to adjust it yourself.

**Comment by alexwenbj** [comment]
@srs888001 Got it, Thank you.

**Comment by alexwenbj** [comment]
@srs888001 It seems that all the modern browsers are support this property.
https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit
