### ISSUE TITLE
electron桌面端录制回放白屏！！

### ISSUE THREAD

**Issue by softmaxs** [AgoraIO-Usecase/eEducation#18]
window10房间中开启云端录制，结束录制后点击录制回放白屏。

**Comment by srs888001** [comment]
这个需要你提供日志，另外你是否修改过东西？

**Comment by softmaxs** [comment]
@srs888001 刚重新把github上的源码下载重新运行，按照README上的文档安装运行（win10 64位），没修改任何代码，只修改demo.env配置，然后测试录制视频点机白屏，你们那边是正常的吗？
日志：
ERROR   15:34:34:631   9084; agora::media::VideoEngine::captureIndexFromDeviceId: failed to get device index for device AgoraCapInvalid

**Comment by Matrixbirds** [comment]
我们这边没法复现，你这边是管理员身份运行的吗？

**Comment by softmaxs** [comment]
登录选择教师身份->小班课->课程开始->开始录制->停止录制->点击录制回放->白屏；没修改过任何不是配置的代码。

**Comment by Matrixbirds** [comment]
我尝试了一样的操作 没法复现，你这边是不是有开代理导致了页面加载异常？
