### ISSUE TITLE
Web demo: max hosts hardcoded to 1 for big-classroom/lecture-hall?

### ISSUE THREAD

**Issue by iNishant** [AgoraIO-Usecase/eEducation#180]
I confirmed with Agora support that the web demo code starts giving "room full" errors because apparently there is max hosts = 1 for the demo code. Any idea how we can remove this restriction?

**Comment by srs888001** [comment]
In our lecture-hall class, there is only one teacher, and there is no limit for students. 
At present, you can't use the situation of multiple teachers.
