### ISSUE TITLE
<--- Last few GCs --->  [56906:0x1b169f0]    50347 ms: Mark-sweep 1382.4 (1424.4) -> 1382.3 (1424.9) MB, 642.1 / 0.0 ms  (average mu = 0.103, current mu = 0.008) allocation failure scavenge might not succeed [56906:0x1b169f0]    50977 ms: Mark-sweep 1383.2 (1424.9) -> 1383.1 (1426.4) MB, 628.8 / 0.0 ms  (average mu = 0.055, current mu = 0.002) allocation failure scavenge might not succeed   <--- JS stacktrace --->

### ISSUE THREAD

**Issue by Nondukishor** [AgoraIO-Usecase/eEducation#183]
Webpack: Starting ...

  ✔ Compile modules
  ✔ Build modules
  ❯ Optimize modules (96%)
    → After chunk asset optimization ...

<--- Last few GCs --->

[56906:0x1b169f0]    50347 ms: Mark-sweep 1382.4 (1424.4) -> 1382.3 (1424.9) MB, 642.1 / 0.0 ms  (average mu = 0.103, current mu = 0.008) allocation failure scavenge might not succeed
[56906:0x1b169f0]    50977 ms: Mark-sweep 1383.2 (1424.9) -> 1383.1 (1426.4) MB, 628.8 / 0.0 ms  (average mu = 0.055, current mu = 0.002) allocation failure scavenge might not succeed

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x25e19bfd452b]
    1: StubFrame [pc: 0x25e19bf225d4]
Security context: 0x154d0682ee11 <JSObject>
    2: addMappingWithCode [0x12ae4771e849] [/media/nipu/practice/education/node_modules/source-map/lib/source-node.js:~150] [pc=0x25e19c7fdd0a](this=0x081b723884f1 <JSGlobal Object>,mapping=0x2140685b46d9 <Object map = 0x1429fd62ad11>,code=0x32f7b5429a41 <String[4]:  << >)
    3: /* anonymous */ [0x3c4dbf4022c9] [/media/...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x7f95752ad46c node::Abort() [/lib/x86_64-linux-gnu/libnode.so.64]
 2: 0x7f95752ad4b5  [/lib/x86_64-linux-gnu/libnode.so.64]
 3: 0x7f95754d9e6a v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/lib/x86_64-linux-gnu/libnode.so.64]
 4: 0x7f95754da0e1 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/lib/x86_64-linux-gnu/libnode.so.64]
 5: 0x7f9575874c66  [/lib/x86_64-linux-gnu/libnode.so.64]
 6: 0x7f9575886043 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/lib/x86_64-linux-gnu/libnode.so.64]
 7: 0x7f9575886930 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/lib/x86_64-linux-gnu/libnode.so.64]
 8: 0x7f957588891d v8::internal::Heap::AllocateRawWithLigthRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/lib/x86_64-linux-gnu/libnode.so.64]
 9: 0x7f9575888975 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/lib/x86_64-linux-gnu/libnode.so.64]
10: 0x7f9575854dda v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/lib/x86_64-linux-gnu/libnode.so.64]
11: 0x7f9575ae031e v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/lib/x86_64-linux-gnu/libnode.so.64]
12: 0x25e19bfd452b 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by pramodhk** [comment]
Getting the same issue in angular code while running the command 
"sudo npm runn prod"

Can anyone please help me on this

**Comment by srs888001** [comment]
as the error indicates, your project is OOM. When does this happen? Did you change anything to the project?

**Comment by Nondukishor** [comment]
solved

**Comment by Troyegloria** [comment]
> solved

how do?
