### ISSUE TITLE
web 信令不稳定

### ISSUE THREAD

**Issue by seasun** [AgoraIO-Usecase/eEducation#19]
你好，请问原生版信令SDK什么时候可以上线，发现web sdk，经常会出现一些如下问题，发送，接收方都在频道内，但是接收方有时会接收不到什么消息，但没有掉线的回掉；
也有出现收到广播的消息，却不能较即时收到P2P消息，而是阻塞一段时间一次性收到P2P的消息；
登出信令现在只有101与102两个码，不管是被T还是真正断网都只返回102，这样做不到原生SDK的被T提示，也没法做到重连的功能。

**Comment by seasun** [comment]
由于信令是业务逻辑的保证，现在产品有点尴尬。

**Comment by sayiwen** [comment]
我这边也同样的问题，正常出现websocket 已关闭错误。这个错误又抓不到，也不会自动重新连接。太尴尬了

**Comment by menthays** [comment]
- web 信令 1.4.0目前已经修复了很多重连，掉线和错误码的问题，您可以尝试替换一下
- 目前我们改良了项目的架构，所有服务端客户端之间的数据交换逻辑全部抽到了data provider中，您可以尝试一些别的方案来实现data provider (socket.io/我们的信令/您自己可能已有的服务)
- 正在尝试将 C++ 信令封装成 Node Addon 中 :innocent:

**Comment by seasun** [comment]
@menthays  期待，希望能native signal sdk能在这个月上；我们自己搞肯定不现实了

**Comment by menthays** [comment]
最新稳定版已切换到RTM
