### ISSUE TITLE
Cloud recording full screen

### ISSUE THREAD

**Issue by AhmedMamdouh93** [AgoraIO-Usecase/eEducation#19]
I want to record full screen chat and whiteboard everything ,but when i start record and stop record i get 3 .ts files and 1 .m3u8 file i merge them into one mp4 file , i get only audio output can anyone help me please?

**Comment by srs888001** [comment]
Our demo only shows the recording of teachers' videos in merging mode. You need to refer to `https://docs.agora.io/en/cloud-recording/product_cloud_recording?platform=All%20Platforms` to realize this function.

**Comment by jackzro** [comment]
how can i get recorded file like m3u8 file and others ??

**Comment by plutoless** [comment]
@jackzro it will be uploaded to the OSS store you configured.

**Comment by jackzro** [comment]
@plutoless https://github.com/AgoraIO-Usecase/eEducation/tree/master/education_web is this demo provide code to store the file to amazon aws ??

**Comment by jackzro** [comment]
@plutoless @srs888001 when i hit api query and stop i got error "code": 404, i dont kow what i am missing ? and when i check my s3 i only got 1 .m3u8 file and there is no .ts file , do you guys know how to solve it ?

**Comment by plutoless** [comment]
@jackzro this demo does not support aws. For the moment only Alibaba Cloud OSS is supported.
