### ISSUE TITLE
 setAudioRecordingDevice(deviceid) 不起作用

### ISSUE THREAD

**Issue by seasun** [AgoraIO-Usecase/eEducation#20]
![image](https://user-images.githubusercontent.com/1314160/43712561-2ec30d06-99a9-11e8-9e2c-6b99196afc35.png)
 已确保deviceId是没有错

**Comment by menthays** [comment]
您好，可以提供版本与平台信息么，因为我们本地无法复现这个问题，另外设备是虚拟设备么？

此外您可以通过 setLog 接口生成 log 文件查看相关api的调用是否生效。

**Comment by menthays** [comment]
no reponse recv
