### ISSUE TITLE
苹果系统CPU占用率过高

### ISSUE THREAD

**Issue by sayiwen** [AgoraIO-Usecase/eEducation#22]
您好，我发现node版本SDK在苹果系统CPU占用率太高了，运行一会就风扇转个不停，卡的很。不知道是我配置的版本还是什么原因。

**Comment by menthays** [comment]
您好，可以提供一些具体的数值么，因为我们已经针对 electron sdk 进行了一次性能优化，尤其是屏幕共享部分，cpu占用已经降低过接近三分之一。

此外，electron 本身也存在一些性能问题，我们一直在尝试做各方面的优化，如果您有什么好的建议或者相关资料，欢迎随时给我们提。
