### ISSUE TITLE
Agora-eEducation-v4.0.1-alpha education_web 安装后无法进入直播间

### ISSUE THREAD

**Issue by mini12com** [AgoraIO-Usecase/eEducation#29]
![20190518180556](https://user-images.githubusercontent.com/7311493/57968014-ac584780-7997-11e9-8a54-11352f7470f8.png)

首次安装后 npm run start 打开后无法进入直播间，请问是什么问题，是不是需要额外做什么配置，应该怎么排查呢？万分感谢

**Comment by mini12com** [comment]
centos7 64位

**Comment by menthays** [comment]
centos7 64位是指？ 目前此项目clone之后是可以直接连接我们的demo server直接使用的

**Comment by mini12com** [comment]
> centos7 64位是指？目前此项目clone之后是可以直接连接我们的demo server直接使用的

就是运行环境是centos7 64位的，clone education_web之后，改了.env 文件的APPID 运行访问进入登录页面，无法登录进直播间。

**Comment by mini12com** [comment]
@menthays  另外您说的demo server 是education_server 这个项目吗，这个项目我npm install 的时候报错，安装agora-node-rtm时报错缺少 IAgoraService.h
具体错误如下：
`make: Entering directory `/home/wwwtest/eEducation-4.0.1-alpha/education_server/node_modules/agora-node-rtm/build'
  CXX(target) Release/obj.target/agorasdk/addon/node_uid.o
  CXX(target) Release/obj.target/agorasdk/addon/node_napi_api.o
../addon/node_napi_api.cpp: In function ?.api_status napi_get_value_uint32_(const v8::Local<v8::Value>&, uint32_t&)?.
../addon/node_napi_api.cpp:34:33: warning: ?.int32_t v8::Value::Uint32Value() const?.is deprecated (declared at /root/.node-gyp/10.15.1/include/node/v8.h:2477): Use maybe version [-Wdeprecated-declarations]
     result = value->Uint32Value();
                                 ^
../addon/node_napi_api.cpp: In function ?.api_status napi_get_value_int32_(const v8::Local<v8::Value>&, int32_t&)?.
../addon/node_napi_api.cpp:50:32: warning: ?.nt32_t v8::Value::Int32Value() const?.is deprecated (declared at /root/.node-gyp/10.15.1/include/node/v8.h:2478): Use maybe version [-Wdeprecated-declarations]
     result = value->Int32Value();
                                ^
../addon/node_napi_api.cpp: In function ?.api_status napi_get_value_double_(const v8::Local<v8::Value>&, double&)?.
../addon/node_napi_api.cpp:59:33: warning: ?.ouble v8::Value::NumberValue() const?.is deprecated (declared at /root/.node-gyp/10.15.1/include/node/v8.h:2475): Use maybe version [-Wdeprecated-declarations]
     result = value->NumberValue();
                                 ^
  CXX(target) Release/obj.target/agorasdk/addon/node_async_queue.o
  CXX(target) Release/obj.target/agorasdk/addon/rtm_controller.o
In file included from ../addon/rtm_controller.cc:4:0:
../addon/rtm_controller.h:21:27: fatal error: IAgoraService.h: No such file or directory
 #include "IAgoraService.h"
                           ^
compilation terminated.
make: *** [Release/obj.target/agorasdk/addon/rtm_controller.o] Error 1
make: Leaving directory `/home/wwwtest/eEducation-4.0.1-alpha/education_server/node_modules/agora-node-rtm/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/nodejs/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 3.10.0-514.26.2.el7.x86_64
gyp ERR! command "/usr/local/nodejs/bin/node" "/usr/local/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/wwwtest/eEducation-4.0.1-alpha/education_server/node_modules/agora-node-rtm
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN server@1.0.0 No repository field.`

**Comment by menthays** [comment]
非常抱歉，首先回复您一开始的那个问题，原因在于我们线上部署的 demo server使用的appid 和您的不一致，因此消息不通，这个确实是我们一开始疏忽的。

因此假如需要使用您自己的appid，那么也就需要部署一个使用该 appid 的 server 端，也就是education_server及whiteboard_server; 至于您这个报错，是因为缺少LInux Agora RTM 相关的文件，详细内容可以参考https://github.com/AgoraIO-Community/Agora-RTM-Nodejs，该项目还不是很成熟，限制较多：
    1. 使用npm install --ignore-scripts 阻止该项目自动编译
    2. 手动进入node_modules/agora-rtm-nodejs，按照Agora-RTM-Nodejs这个项目readme说明，下载Agora RTM for Linux后按照说明一步一步配置好服务器环境（目前可能仅支持Ubuntu）
    3. 在node_modules/agora-rtm-nodejs运行npm install进行编译

有个简便的方式：如果您有docker环境，可以运行Agora-RTM-Nodejs下的dockerfile，将会完成编译并自动复制到外部目录
