### ISSUE TITLE
请问BASE_URL填什么

### ISSUE THREAD

**Issue by SanChunAndrroid** [AgoraIO-Usecase/eEducation#35]
请问BASE_URL填什么

**Comment by plutoless** [comment]
填你自己的服务器，需要参考https://github.com/AgoraIO-Usecase/eEducation/tree/master/education_server 通过docker部署你自己的服务器环境

**Comment by SanChunAndrroid** [comment]
有点复杂（小白一个）在本地可以部署测试吗

**Comment by plutoless** [comment]
本地用虚拟机+docker起环境然后用localhost访问也是可以的

**Comment by SanChunAndrroid** [comment]
我是windows 也可以吗

**Comment by SanChunAndrroid** [comment]
如何快速集成这个互动课堂 一定要自己搭服务器吗

**Comment by plutoless** [comment]
windows装linux虚拟机也可以的。
目前必须要有后台，后者你可以直接从release下载我们编译好的版本体验

**Comment by SanChunAndrroid** [comment]
哦哦，那请问android版跟ios版是否能够互通（好像没有现成的移动端版本体验）

**Comment by plutoless** [comment]
android我可以让研发准备一个，ios可能不行

**Comment by SanChunAndrroid** [comment]
好的 等待你的android版本 万分感谢

**Comment by SanChunAndrroid** [comment]
这个搭建服务器的教程更详细点吗 搭了好久自己搭不起来

**Comment by plutoless** [comment]
https://github.com/AgoraIO-Usecase/eEducation/tree/master/education_server

**Comment by SanChunAndrroid** [comment]
每个步骤（最好配点图）哈哈

**Comment by SanChunAndrroid** [comment]
怎样才标志搭建成功

**Comment by SanChunAndrroid** [comment]
搭建中报错npm WARN server@1.0.0 No repository field.

**Comment by plutoless** [comment]
Warn无所谓的 不是错误

**Comment by SanChunAndrroid** [comment]
是error
gyp: binding.gyp not found (cwd: /usr/src/app) while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 5.0.0-25-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/src/app
gyp ERR! node -v v8.16.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! server@1.0.0 build:addon: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the server@1.0.0 build:addon script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-08-30T08_09_21_007Z-debug.log
**_### **ERROR: Service 'sentry' failed to build: The command '/bin/sh -c cd /usr/src/app/agora-rtm-nodejs && npm install --ignore-scripts && npm run build:addon && npm run build:ts' returned a non-zero code: 1**_**

**Comment by menthays** [comment]
#37
