### ISSUE TITLE
Uncaught Error: \\?\C:\Users\user\Desktop\agora-education\eEducation\education_electron\node_modules\agora-electron-sdk\build\Release\agora_node_ext.node is not a valid Win32 application.

### ISSUE THREAD

**Issue by WildHorse19** [AgoraIO-Usecase/eEducation#38]
This error was thrown during launch of demo application. Only white screen shown. 
Steps to reproduce :
git clone https://github.com/AgoraIO-Usecase/eEducation
cd education_electron
npm install
npm run dev 
(screenshot attached
![Untitled](https://user-images.githubusercontent.com/41179841/64955814-dd874c80-d891-11e9-9932-5daea02dece9.jpg)
)

**Comment by menthays** [comment]
Since agora sdk for windows only support win32, you have to install 32-bit electron, using `npm install electron -D --arch=ia32`.
