### ISSUE TITLE
Error: this room is full (房间人数已满)

### ISSUE THREAD

**Issue by lemonheadhs** [AgoraIO-Usecase/eEducation#40]
I setup this demo, run a few of tests using the same room name (roomUuid). After a certain point of time, i can no longer enter the room, the "entry" edu api call failed with error message: "You can't join this room because this room is full" (房间人数已满，不能进入)

I wonder where to find documents about this restriction of Edu Api ? And how can i mitigate the issue?

**Comment by lemonheadhs** [comment]
Oh, some additional info should be added: 
The room is a one-to-one class room, and many different browsers may have been used to enter/leave this room, so each time the user uuid logged into the room might be different.

**Comment by srs888001** [comment]
You can look at point 4 of the link below.
`https://github.com/AgoraIO-Usecase/eEducation/wiki/eEducation-6.0.0-Project-Guide#restriction`
