### ISSUE TITLE
Unable to start education_server

### ISSUE THREAD

**Issue by mohammedrafathz** [AgoraIO-Usecase/eEducation#41]
When I run `docker-compose up` in /education_server, following logs are generated

>Starting education_server_redis_1 ... done
Starting education_server_sentry_1 ... done
Attaching to education_server_redis_1, education_server_sentry_1
redis_1   | 1:C 30 Nov 2019 09:29:29.560 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1   | 1:C 30 Nov 2019 09:29:29.560 # Redis version=5.0.6, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1   | 1:C 30 Nov 2019 09:29:29.560 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis_1   | 1:M 30 Nov 2019 09:29:29.565 * Running mode=standalone, port=6379.
redis_1   | 1:M 30 Nov 2019 09:29:29.565 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1   | 1:M 30 Nov 2019 09:29:29.565 # Server initialized
redis_1   | 1:M 30 Nov 2019 09:29:29.566 * DB loaded from disk: 0.001 seconds
redis_1   | 1:M 30 Nov 2019 09:29:29.566 * Ready to accept connections
education_server_sentry_1 exited with code 139

The issue seems to be related to redis:alpine image. I tried changing the somaxconn value to something greater from inside the redis:alpine container but it says the file system is read-only.

**Comment by Matrixbirds** [comment]
You can try the latest version on the master branch.

**Comment by mohammedrafathz** [comment]
Netless is not allowing me to sign up & everything is in Chinese.

How do I generate all those sets of tokens mentioned in the .env.example file?
Please do mention instructions on locating the other env variables too.

**Comment by Matrixbirds** [comment]
You could find Netless english doc [here](https://developer-en.netless.link/).

**Comment by mohammedrafathz** [comment]
This [page](https://developer-en.netless.link/docs/blog/blog-begin-netless/) provides instruction on creating a netless account but, It says the mobile number is a required field. I don't own a Chinese mobile number & I have tried using Indian numbers & it doesn't work.

**Comment by plutoless** [comment]
@mohammedrafathz  sry i'm helping contacting netless people. they will answer here some time later

**Comment by alwaysmavs** [comment]
@mohammedrafathz We are working on this recently. If you are in a hurry, we can give you an sdkToken as a test first.

**Comment by alwaysmavs** [comment]
@mohammedrafathz my email is rick@netless.link

**Comment by mohammedrafathz** [comment]
It would be really helpful if you provide info on environment variables in the readme file.

**Comment by plutoless** [comment]
which platform are you talking about? i think we have explained the user-defined variables in readme already in master branch.
