### ISSUE TITLE
education_server docker-compose up 失败

### ISSUE THREAD

**Issue by zhu8655** [AgoraIO-Usecase/eEducation#44]
Step 11/14 : RUN cd /usr/src/app/agora-rtm-nodejs && npm install --ignore-scripts && npm run build:addon && npm run build:ts
 ---> Running in edcbc32b1443
npm WARN server@1.0.0 No repository field.

added 114 packages from 142 contributors and audited 214 packages in 17.344s
found 0 vulnerabilities

npm ERR! missing script: build:addon

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-15T08_08_59_396Z-debug.log
ERROR: Service 'sentry' failed to build: The command '/bin/sh -c cd /usr/src/app/agora-rtm-nodejs && npm install --ignore-scripts && npm run build:addon && npm run build:ts' returned a non-zero code: 1

在运行docker-compose up时出现的错误，请问要如何解决

**Comment by plutoless** [comment]
这边再等两天吧，过几天我们会出一个不需要后台的版本
