### ISSUE TITLE
docker-compose up --force-recreate命令报错

### ISSUE THREAD

**Issue by stogui** [AgoraIO-Usecase/eEducation#46]
Step 10/12 : RUN cd /usr/src/app && npm install && npm run prestart
 ---> Running in beca0d9bc7b2
npm WARN server@1.0.0 No repository field.

added 114 packages from 142 contributors and audited 214 packages in 31.643s
found 0 vulnerabilities

> server@1.0.0 prestart /usr/src/app
> tsc

src/components/sentry/index.ts(77,7): error TS2531: Object is possibly 'null'.
src/components/sentry/index.ts(82,7): error TS2531: Object is possibly 'null'.
src/components/sentry/index.ts(101,17): error TS2345: Argument of type 'AgoraRtmChannel | null' is not assignable to parameter of type 'AgoraRtmChannel | PromiseLike<AgoraRtmChannel> | undefined'.
  Type 'null' is not assignable to type 'AgoraRtmChannel | PromiseLike<AgoraRtmChannel> | undefined'.
src/components/sentry/index.ts(103,7): error TS2531: Object is possibly 'null'.
src/components/sentry/index.ts(131,7): error TS2531: Object is possibly 'null'.
src/components/sentry/index.ts(171,15): error TS2531: Object is possibly 'null'.
src/components/sentry/index.ts(173,9): error TS2531: Object is possibly 'null'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! server@1.0.0 prestart: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the server@1.0.0 prestart script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-12-25T16_09_59_664Z-debug.log
ERROR: Service 'sentry' failed to build: The command '/bin/sh -c cd /usr/src/app && npm install && npm run prestart' returned a non-zero code: 2

**Comment by plutoless** [comment]
建议过两天参考新的master版本，那个不依赖目前的后台
