### ISSUE TITLE
【问题】【web】没看懂rtm的消息是如何发送和接收的

### ISSUE THREAD

**Issue by maicWorkGithub** [AgoraIO-Usecase/eEducation#47]
> 纯粹的代码逻辑问题，我是小白

第一，先说一下基本的逻辑，这个部分我知道的。两个角色，老师和学生。初始化和加入一个房间之后，任何一方，调用client.sendMessage方法，会向整个channel发送消息（这个没错吧）。如果这个没错，下面就是我的问题了

我把这个项目clone下来之后，试着自己写后端，替换你们的后端服务。

用户聊天部分，点击发送按钮之后

https://github.com/AgoraIO-Usecase/eEducation/blob/47dc2192d869c790c58bac735ef07b181d8965ce/education_web/src/stores/app/room.ts#L654-L669

可以看到，这部分代码只有两个逻辑，第一句话是调用了一个线上的API，这个API的返回值就是成功与否，也没有使用。第二句话是把这个message push到了一个本地的数组里面，用于UI展示，所以这个消息是怎么发送出去的？没有调用RTM的方法啊，这个RTM的方法在：

https://github.com/AgoraIO-Usecase/eEducation/blob/47dc2192d869c790c58bac735ef07b181d8965ce/education_web/src/sdk/education/core/rtm/index.ts#L237-L240

我全局搜了这个方法，发现压根没使用过。

求大佬解答一下。先谢谢了

**Comment by maicWorkGithub** [comment]
我自己试了一下，在room.ts那个代码块里调用rtm的sendMessage方法，发现事件被触发了，这才是你们文档上写的逻辑呀。

另外一个问题 https://docs.agora.io/cn/rtc/restfulapi 这个API是干嘛用的？跟你们教育云项目的API有啥关系？

**Comment by srs888001** [comment]
所以这个消息是怎么发送出去的？没有调用RTM的方法啊
--------------------
这个是我们后台服务会帮助我们发RTM。

https://docs.agora.io/cn/rtc/restfulapi 
--------------------
这个是我们后台服务对外暴露的Api。 客户端http请求到后台服务， 后台服务会RTM广播消息。

自己完全实现后台，需要考虑的事情其实还蛮多的， 如果你真的需要自己实现后台，建议你联系我们的支持同学。

**Comment by maicWorkGithub** [comment]
还好我没有菜到代码看不懂。

这样做有什么好处吗，不用你们文档里写的SDK 里的API ？

**Comment by srs888001** [comment]
我们现在应该没有直接调用RTM对应的接口，都是通过 https://docs.agora.io/cn/rtc/restfulapi里面的接口调用的

**Comment by maicWorkGithub** [comment]
你们现在的流程是
1，创建RTM示例的时候，监听ChannelMessage事件
2，用户发消息，请求你们后端Restful API
3，你们后端服务广播消息，通过websocket跟RTM SDK通讯，然后emit ChannelMessage事件

是这样的吗？

另外你没有回答我的第二个问题，只是重复了上面说过的话。为什么你们选择使用调用后端API的方式，而不是使用你们SDK里自带的API？这样有什么好处？

**Comment by srs888001** [comment]
链接搞错了， 你可以看这个：https://agoradoc.github.io/cn/edu-cloud-service/restfulapi/
好处就是HTTP目前而言方便扩展，比如要做负载均衡

**Comment by maicWorkGithub** [comment]
我上面说的流程对吗？

这个链接我一直在看，就是看这个文档倒推你们后端的逻辑……。

如果我自己写后端服务的话，怎么出发本地的ChannelMessage事件？

**Comment by srs888001** [comment]
流程基本就是这样。   你后台要加入RTM，然后有request的时候，通过这个发rtm消息。

**Comment by maicWorkGithub** [comment]
怎么每次都回答一个问题，是我问的方式不对吗，每次只问一个问题比较好？

上面的第二个问题是：如果我自己写后端服务的话，怎么写才能触发本地的ChannelMessage事件？

**Comment by srs888001** [comment]
就是你后端加入一个rtm实例， 你可以通过这个rtm实例发消息

**Comment by maicWorkGithub** [comment]
你指的是这部分的文档？
https://docs.agora.io/cn/Real-time-Messaging/API%20Reference/RTM_cpp/index.html

**Comment by srs888001** [comment]
是的

**Comment by maicWorkGithub** [comment]
我觉得这个部分没有使用文档里的API应该在文档里面或者最起码这个项目的readme里体现出来，并说明一下这是为了负载均衡。因为这个是学习项目，我这个逻辑找了一天……debug我自己写的，debug你们线上编译好的项目。

**Comment by maicWorkGithub** [comment]
我又来了，这次没看懂学生的语音和视频是怎么publish和subscribe的，也没有你们文档上说的开启双流模式，启用1+N的方式。

**Comment by maicWorkGithub** [comment]
这是要提工单的意思嘛……

**Comment by yoreland** [comment]
@maicWorkGithub 这个demo一方面是展示利用rtc和rtm demo实现教育场景化,另一方面未来这个demo会变成封装好的开箱即用的教育行业的“sdk”, 所以关于发送消息,发送音视频数据的在底层sdk的实现方式,的确会做实现上的封装.
如果只是想了解我们sdk在各个功能上的表现也可以移步 AgoraIO/APIExample里面体验的.

**Comment by maicWorkGithub** [comment]
@yoreland AgoraIO/APIExample 在你们的组织里没找到这个项目。能不能给个链接？

我还是想知道学生的音视频是怎么订阅和发布的，因为看完文档之后，发现你们并没有按照你们的文档来组织你们的架构，这个让人很迷惘的。是不是应该在文档里或项目readme里写上，遇到性能瓶颈的时候，应该朝哪个方向去优化？

而且就第一个问题来说，你们用后端RTM的服务代替直接使用RTM，去做大量并发的负载均衡，我觉得这是一个很不错的点，而且已经集成到了你们的SDK里面了，这么好的点为什么不写出来呢？小公司去实践，寻找解决方案，可能要小半年呢。

我看了很多你们的DEMO，做的也都不错，但是真正的产品，就是这个了，想模仿一下，你们就一句封装，就拒绝我们了？

**Comment by Chen-Alexander** [comment]
@maicWorkGithub  你好，首先很感谢你所发现的问题和提出的建议。同时，像“用后端RTM的服务代替直接使用RTM”、“遇到性能瓶颈的时候，应该朝哪个方向去优化”，这些点我们会收集并在合适的时候公布；同时readme中更多的是如何让开发者快速的跑通我们的项目。关于音视频是怎么订阅和发布的问题，稍后同事会给予解答。再次感谢对于我们SDK和产品的肯定。

**Comment by maicWorkGithub** [comment]
@Chen-Alexander 能不能加个群什么的，我也有你们的售后群。这一个问题17天没了……

**Comment by plutoless** [comment]
@maicWorkGithub 不好意思回复慢了，这边能不能告知一下售后群的群名或者我们联系到您的方式？我这边安排研发和您直接沟通一下

**Comment by maicWorkGithub** [comment]
微信：
![image](https://user-images.githubusercontent.com/15863224/103593157-04a6d900-4f30-11eb-9605-125589cabe8b.png)
