### ISSUE TITLE
Custom whiteboard application

### ISSUE THREAD

**Issue by RamanHacks** [AgoraIO-Usecase/eEducation#5]
How to enable only RTC Audio feature (and not video feature) when building a custom whiteboard application?

**Comment by plutoless** [comment]
you can call disableVideo on rtcEngine when joining channel. but then you shall adapt corresponding ui changes caused by this, e.g. change original video canvas to a audio only placeholder etc.

**Comment by RamanHacks** [comment]
Thanks for the reply. I got your point.
