### ISSUE TITLE
education_electron项目install的时候报错

### ISSUE THREAD

**Issue by xml4cn** [AgoraIO-Usecase/eEducation#54]
在education_electron根目录执行：cnpm install 报错
系统：win10 64位 node：v12.14.0   cnpm@6.1.1  npm@6.13.4
master分钟，几分钟前clone的代码：  f4fe7bda0f51726f4eda3f20be474cc84a6392cd

```
[2/8] scripts.install agora-electron-sdk@^2.4.0-alpha run "just install", root: "E:\\projects\\eEducation\\education_electron\\node_modules\\_agora-electron-sdk@2.9.0@agora-electron-sdk"
[14:25:24] ■ started 'install'
[14:25:24] x Error detected while running 'install'
[14:25:24] x ------------------------------------
[14:25:24] x TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.join (path.js:375:7)
    at module.exports.getArgvFromPkgJson (E:\projects\eEducation\education_electron\node_modules\_agora-electron-sdk@2.9.0@agora-electron-sdk\scripts\npm_argv.js:15:27)
    at E:\projects\eEducation\education_electron\node_modules\_agora-electron-sdk@2.9.0@agora-electron-sdk\just-task.js:54:57
    at _wrapFunction (E:\projects\eEducation\education_electron\node_modules\_just-task@0.13.3@just-task\lib\wrapTask.js:13:36)
    at install (E:\projects\eEducation\education_electron\node_modules\_undertaker@1.2.1@undertaker\lib\set-task.js:13:15)
    at bound (domain.js:419:14)
    at runBound (domain.js:432:12)
    at asyncRunner (E:\projects\eEducation\education_electron\node_modules\_async-done@1.3.2@async-done\index.js:55:18)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
[14:25:24] x ------------------------------------
[14:25:24] x Error previously detected. See above for error messages.
[npminstall:runscript:error] agora-electron-sdk@^2.4.0-alpha scripts.install run "just install" error: Error [RunScriptError]: Run "C:\Windows\system32\cmd.exe /d /s /c just install" error, exit code 1
    at ChildProcess.<anonymous> (C:\Users\WIF\AppData\Roaming\npm\node_modules\cnpm\node_modules\runscript\index.js:96:21)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  name: 'RunScriptError',
  stdio: [Object]
}
× Install fail! RunScriptError: post install error, please remove node_modules before retry!
Run "C:\Windows\system32\cmd.exe /d /s /c just install" error, exit code 1
RunScriptError: Run "C:\Windows\system32\cmd.exe /d /s /c just install" error, exit code 1
    at ChildProcess.<anonymous> (C:\Users\WIF\AppData\Roaming\npm\node_modules\cnpm\node_modules\runscript\index.js:96:21)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
npminstall version: 3.25.2
npminstall args: C:\Program Files\nodejs\node.exe C:\Users\WIF\AppData\Roaming\npm\node_modules\cnpm\node_modules\npminstall\bin\install.js --fix-bug-versions --china --userconfig=C:\Users\WIF\.cnpmrc --d
--userconfig=C:\Users\WIF\.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://r.npm.taobao.org
```

**Comment by xml4cn** [comment]
在线等

**Comment by Matrixbirds** [comment]
麻烦看下edu_web目录 这个electron项目已经不用了

**Comment by xml4cn** [comment]
晕晕晕，搞了一下午

**Comment by xml4cn** [comment]
可是我这边要基于electron来做，现在声网的sdk是不再支持electron 了吗？

**Comment by plutoless** [comment]
edu_web包含了electron

**Comment by plutoless** [comment]
目录我们最近会整理一下

**Comment by zy0228** [comment]
> 目录我们最近会整理一下
edu_web 我尝试运行 npm run pack:win 进行打包成应用失败， 请问我参照的package.json 下的命令没错吧

**Comment by Matrixbirds** [comment]
@zy0228 
`package.json`
这块需要您替换一下`agora_electron`这里的代码按照如下配置：
```json
  "agora_electron": {
    "electron_version": "5.0.8",
    "prebuilt": true,
    "platform": "darwin"
  },
```  

windows上我们推荐手动安装一遍electron@5.0.8 win32版本   
`npm i electron@5.0.8 --arch=ia32`   
 然后再重新安装一遍agora-electron-sdk (目前demo里是2.9.1-beta.4)  
`npm i agora-electron-sdk@2.9.1-beta.4`

**Comment by zy0228** [comment]
就如你所说的 我都完整的试了一下 还是会有报错：
               Error: C:\Users\Administrator\Desktop\edu_web\node_modules\_app-b
uilder-bin@3.4.3@app-builder-bin\win\x64\app-builder.exe exited with code ERR_EL
ECTRON_BUILDER_CANNOT_EXECUTE

**Comment by Matrixbirds** [comment]
您好 这块还有别的完整报错日志吗？看这部分日志感觉是electron-builder这块有异常了。cmd打开的时候可能需要授权用管理员身份运行才能拿到执行权限。如果还是不行的话 可以上传一份你的package-lock.json和package.json给到我吗？

**Comment by zy0228** [comment]
`{
  "name": "agora-edu-web",
  "version": "3.0.0",
  "private": true,
  "homepage": ".",
  "main": "./src/index.tsx",
  "agora_electron": {
    "electron_version": "5.0.8",
    "prebuilt": true,
    "platform": "darwin"
  },
  "build": {
    "extraMetadata": {
      "main": "build/index.js"
    },
    "productName": "AgoraEducation",
    "appId": "io.agora.education",
    "files": [
      "build/**/*"
    ],
    "dmg": {
      "contents": [
        {
          "x": 130,
          "y": 220
        },
        {
          "x": 410,
          "y": 220,
          "type": "link",
          "path": "/Applications"
        }
      ]
    },
    "mac": {
      "icon": "icons/favicon.png",
      "entitlements": "entitlements.mac.plist",
      "hardenedRuntime": true,
      "extendInfo": {
        "NSMicrophoneUsageDescription": "AgoraEdu Classroom acquire your microphone permission",
        "NSCameraUsageDescription": "AgoraEdu Classroom acquire your camera permission"
      }
    },
    "win": {
      "icon": "icons/favicon.png",
      "target": [
        {
          "target": "nsis",
          "arch": [
            "ia32"
          ]
        }
      ]
    },
    "linux": {
      "icon": "icons/favicon.png",
      "target": [
        "deb",
        "rpm",
        "snap",
        "AppImage"
      ],
      "category": "Development"
    },
    "directories": {
      "buildResources": "assets",
      "output": "release"
    }
  },
  "dependencies": {
    "@material-ui/core": "^4.5.1",
    "@material-ui/icons": "^4.5.1",
    "@netless/react-seek-slider": "^1.0.4",
    "@types/jest": "^24.0.19",
    "@types/lodash": "^4.14.145",
    "@types/node": "^12.11.1",
    "@types/react": "^16.9.9",
    "@types/react-dom": "^16.9.2",
    "@types/react-router-dom": "^5.1.0",
    "agora-electron-sdk": "^2.9.1-beta.1",
    "agora-rtc-sdk": "3.0.0",
    "agora-rtm-sdk": "^1.2.0",
    "animate.css": "^3.7.2",
    "concurrently": "^5.0.0",
    "cross-env": "^6.0.3",
    "electron-is-dev": "^1.1.0",
    "foreman": "^3.0.1",
    "immutable": "^4.0.0-rc.12",
    "js-md5": "^0.7.3",
    "lodash": "^4.17.15",
    "moment": "^2.24.0",
    "node-sass": "^4.12.0",
    "react": "^16.10.2",
    "react-color": "^2.17.3",
    "react-dom": "^16.10.2",
    "react-draggable": "^4.2.0",
    "react-router-dom": "^5.1.2",
    "react-scripts": "3.2.0",
    "rxjs": "^6.5.3",
    "typescript": "^3.6.4",
    "wait-on": "^3.3.0"
  },
  "scripts": {
    "electron": "cross-env REACT_APP_RUNTIME_PLATFORM=electron ELECTRON_START_URL=http://localhost:3000 concurrently \"npm run electron:web\" \"wait-on http://localhost:3000 && npm run electron:client\"",
    "electron:client": "cross-env electron ./app/",
    "electron:web": "cross-env BROWSER=none react-app-rewired start",
    "electron:copy:web": "cross-env REACT_APP_RUNTIME_PLATFORM=electron react-app-rewired build",
    "electron:copy:electron": "cpx ./app/**/*.js ./build",
    "electron:build": "npm run electron:copy:web && npm run electron:copy:electron",
    "dev": "cross-env REACT_APP_RUNTIME_PLATFORM=web react-app-rewired start",
    "build": "cross-env REACT_APP_RUNTIME_PLATFORM=web react-app-rewired build",
    "test": "react-app-rewired test --env=jsdom",
    "eject": "react-scripts eject",
    "pack:mac": "npm run electron:build && electron-builder --dir",
    "pack:win": "npm run electron:build && electron-builder --win"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@types/ali-oss": "^6.0.4",
    "@types/react-color": "^3.0.1",
    "@types/uuid": "^3.4.6",
    "ali-oss": "^6.3.1",
    "cpx": "^1.5.0",
    "customize-cra": "^0.8.0",
    "devtron": "^1.4.0",
    "electron": "5.0.8",
    "electron-builder": "^21.2.0",
    "electron-debug": "^3.0.1",
    "electron-devtools-installer": "^2.2.4",
    "react-app-rewired": "^2.1.4",
    "source-map-support": "^0.5.16",
    "uuid": "^3.3.3",
    "white-web-sdk": "2.3.17"
  }
}
`

**Comment by zy0228** [comment]
`{
  "name": "agora-edu-web",
  "version": "3.0.0",
  "private": true,
  "homepage": ".",
  "main": "./src/index.tsx",
  "agora_electron": {
    "electron_version": "5.0.8",
    "prebuilt": true,
    "platform": "darwin"
  },
  "build": {
    "extraMetadata": {
      "main": "build/index.js"
    },
    "productName": "AgoraEducation",
    "appId": "io.agora.education",
    "files": [
      "build/**/*"
    ],
    "dmg": {
      "contents": [
        {
          "x": 130,
          "y": 220
        },
        {
          "x": 410,
          "y": 220,
          "type": "link",
          "path": "/Applications"
        }
      ]
    },
    "mac": {
      "icon": "icons/favicon.png",
      "entitlements": "entitlements.mac.plist",
      "hardenedRuntime": true,
      "extendInfo": {
        "NSMicrophoneUsageDescription": "AgoraEdu Classroom acquire your microphone permission",
        "NSCameraUsageDescription": "AgoraEdu Classroom acquire your camera permission"
      }
    },
    "win": {
      "icon": "icons/favicon.png",
      "target": [
        {
          "target": "nsis",
          "arch": [
            "ia32"
          ]
        }
      ]
    },
    "linux": {
      "icon": "icons/favicon.png",
      "target": [
        "deb",
        "rpm",
        "snap",
        "AppImage"
      ],
      "category": "Development"
    },
    "directories": {
      "buildResources": "assets",
      "output": "release"
    }
  },
  "dependencies": {
    "@material-ui/core": "^4.5.1",
    "@material-ui/icons": "^4.5.1",
    "@netless/react-seek-slider": "^1.0.4",
    "@types/jest": "^24.0.19",
    "@types/lodash": "^4.14.145",
    "@types/node": "^12.11.1",
    "@types/react": "^16.9.9",
    "@types/react-dom": "^16.9.2",
    "@types/react-router-dom": "^5.1.0",
    "agora-electron-sdk": "^2.9.1-beta.1",
    "agora-rtc-sdk": "3.0.0",
    "agora-rtm-sdk": "^1.2.0",
    "animate.css": "^3.7.2",
    "concurrently": "^5.0.0",
    "cross-env": "^6.0.3",
    "electron-is-dev": "^1.1.0",
    "foreman": "^3.0.1",
    "immutable": "^4.0.0-rc.12",
    "js-md5": "^0.7.3",
    "lodash": "^4.17.15",
    "moment": "^2.24.0",
    "node-sass": "^4.12.0",
    "react": "^16.10.2",
    "react-color": "^2.17.3",
    "react-dom": "^16.10.2",
    "react-draggable": "^4.2.0",
    "react-router-dom": "^5.1.2",
    "react-scripts": "3.2.0",
    "rxjs": "^6.5.3",
    "typescript": "^3.6.4",
    "wait-on": "^3.3.0"
  },
  "scripts": {
    "electron": "cross-env REACT_APP_RUNTIME_PLATFORM=electron ELECTRON_START_URL=http://localhost:3000 concurrently \"npm run electron:web\" \"wait-on http://localhost:3000 && npm run electron:client\"",
    "electron:client": "cross-env electron ./app/",
    "electron:web": "cross-env BROWSER=none react-app-rewired start",
    "electron:copy:web": "cross-env REACT_APP_RUNTIME_PLATFORM=electron react-app-rewired build",
    "electron:copy:electron": "cpx ./app/**/*.js ./build",
    "electron:build": "npm run electron:copy:web && npm run electron:copy:electron",
    "dev": "cross-env REACT_APP_RUNTIME_PLATFORM=web react-app-rewired start",
    "build": "cross-env REACT_APP_RUNTIME_PLATFORM=web react-app-rewired build",
    "test": "react-app-rewired test --env=jsdom",
    "eject": "react-scripts eject",
    "pack:mac": "npm run electron:build && electron-builder --dir",
    "pack:win": "npm run electron:build && electron-builder --win"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@types/ali-oss": "^6.0.4",
    "@types/react-color": "^3.0.1",
    "@types/uuid": "^3.4.6",
    "ali-oss": "^6.3.1",
    "cpx": "^1.5.0",
    "customize-cra": "^0.8.0",
    "devtron": "^1.4.0",
    "electron": "5.0.8",
    "electron-builder": "^21.2.0",
    "electron-debug": "^3.0.1",
    "electron-devtools-installer": "^2.2.4",
    "react-app-rewired": "^2.1.4",
    "source-map-support": "^0.5.16",
    "uuid": "^3.3.3",
    "white-web-sdk": "2.3.17"
  }
}
`

**Comment by zy0228** [comment]
> 您好 这块还有别的完整报错日志吗？看这部分日志感觉是electron-builder这块有异常了。cmd打开的时候可能需要授权用管理员身份运行才能拿到执行权限。如果还是不行的话 可以上传一份你的package-lock.json和package.json给到我吗？

{
  "name": "agora-edu-web",
  "version": "3.0.0",
  "private": true,
  "homepage": ".",
  "main": "./src/index.tsx",
  "agora_electron": {
    "electron_version": "5.0.8",
    "prebuilt": true,
    "platform": "darwin"
  },
  "build": {
    "extraMetadata": {
      "main": "build/index.js"
    },
    "productName": "AgoraEducation",
    "appId": "io.agora.education",
    "files": [
      "build/**/*"
    ],
    "dmg": {
      "contents": [
        {
          "x": 130,
          "y": 220
        },
        {
          "x": 410,
          "y": 220,
          "type": "link",
          "path": "/Applications"
        }
      ]
    },
    "mac": {
      "icon": "icons/favicon.png",
      "entitlements": "entitlements.mac.plist",
      "hardenedRuntime": true,
      "extendInfo": {
        "NSMicrophoneUsageDescription": "AgoraEdu Classroom acquire your microphone permission",
        "NSCameraUsageDescription": "AgoraEdu Classroom acquire your camera permission"
      }
    },
    "win": {
      "icon": "icons/favicon.png",
      "target": [
        {
          "target": "nsis",
          "arch": [
            "ia32"
          ]
        }
      ]
    },
    "linux": {
      "icon": "icons/favicon.png",
      "target": [
        "deb",
        "rpm",
        "snap",
        "AppImage"
      ],
      "category": "Development"
    },
    "directories": {
      "buildResources": "assets",
      "output": "release"
    }
  },
  "dependencies": {
    "@material-ui/core": "^4.5.1",
    "@material-ui/icons": "^4.5.1",
    "@netless/react-seek-slider": "^1.0.4",
    "@types/jest": "^24.0.19",
    "@types/lodash": "^4.14.145",
    "@types/node": "^12.11.1",
    "@types/react": "^16.9.9",
    "@types/react-dom": "^16.9.2",
    "@types/react-router-dom": "^5.1.0",
    "agora-electron-sdk": "^2.9.1-beta.1",
    "agora-rtc-sdk": "3.0.0",
    "agora-rtm-sdk": "^1.2.0",
    "animate.css": "^3.7.2",
    "concurrently": "^5.0.0",
    "cross-env": "^6.0.3",
    "electron-is-dev": "^1.1.0",
    "foreman": "^3.0.1",
    "immutable": "^4.0.0-rc.12",
    "js-md5": "^0.7.3",
    "lodash": "^4.17.15",
    "moment": "^2.24.0",
    "node-sass": "^4.12.0",
    "react": "^16.10.2",
    "react-color": "^2.17.3",
    "react-dom": "^16.10.2",
    "react-draggable": "^4.2.0",
    "react-router-dom": "^5.1.2",
    "react-scripts": "3.2.0",
    "rxjs": "^6.5.3",
    "typescript": "^3.6.4",
    "wait-on": "^3.3.0"
  },
  "scripts": {
    "electron": "cross-env REACT_APP_RUNTIME_PLATFORM=electron ELECTRON_START_URL=http://localhost:3000 concurrently \"npm run electron:web\" \"wait-on http://localhost:3000 && npm run electron:client\"",
    "electron:client": "cross-env electron ./app/",
    "electron:web": "cross-env BROWSER=none react-app-rewired start",
    "electron:copy:web": "cross-env REACT_APP_RUNTIME_PLATFORM=electron react-app-rewired build",
    "electron:copy:electron": "cpx ./app/**/*.js ./build",
    "electron:build": "npm run electron:copy:web && npm run electron:copy:electron",
    "dev": "cross-env REACT_APP_RUNTIME_PLATFORM=web react-app-rewired start",
    "build": "cross-env REACT_APP_RUNTIME_PLATFORM=web react-app-rewired build",
    "test": "react-app-rewired test --env=jsdom",
    "eject": "react-scripts eject",
    "pack:mac": "npm run electron:build && electron-builder --dir",
    "pack:win": "npm run electron:build && electron-builder --win"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@types/ali-oss": "^6.0.4",
    "@types/react-color": "^3.0.1",
    "@types/uuid": "^3.4.6",
    "ali-oss": "^6.3.1",
    "cpx": "^1.5.0",
    "customize-cra": "^0.8.0",
    "devtron": "^1.4.0",
    "electron": "5.0.8",
    "electron-builder": "^21.2.0",
    "electron-debug": "^3.0.1",
    "electron-devtools-installer": "^2.2.4",
    "react-app-rewired": "^2.1.4",
    "source-map-support": "^0.5.16",
    "uuid": "^3.3.3",
    "white-web-sdk": "2.3.17"
  }
}

**Comment by Matrixbirds** [comment]
您是在master分支拉的代码吗？可以试试看新分支，最近更新了一些新功能，这块可能是旧的代码，拉一下master的education_web试试

**Comment by plutoless** [comment]
@zy0228 如果有完整的build错误日志，也麻烦给一下
