### ISSUE TITLE
就这一个房间突然连不上config 409 其它房间可以 这是什么问题？

### ISSUE THREAD

**Issue by cwg31825** [AgoraIO-Usecase/eEducation#58]
POST https://api.agora.io/scene/apps/24e968a57b874af085d5cc433dcb3d31/v1/rooms/16106076001925/config 409
index.ts:105 [http] POST#https://api.agora.io/scene/apps/24e968a57b874af085d5cc433dcb3d31/v1/rooms/16106076001925/config response params:  {"method":"POST","headers":{"Content-Type":"application/json","Authorization":"Basic ZWExNWY0ZTNhNGM1NDkwM2IyMjU3Mjc2ZjlhOGNhNWE6NGY0ZmEzOWEwYjExNGUzYjg0MWUyZmM4MTM5NDcyM2M="},"body":"{\"roomName\":\"逛庙会上\",\"roleConfig\":{\"host\":{\"limit\":1},\"broadcaster\":{\"limit\":16}}}"}  response:  {"msg":"Room conflict!","code":20409100,"ts":1610699360126}  status:  409  statusText:  
index.ts:105 [http] GET#https://api.agora.io/scene/apps/24e968a57b874af085d5cc433dcb3d31/v1/rooms/16106076001925/config response params:  {"method":"GET","headers":{"Content-Type":"application/json","Authorization":"Basic ZWExNWY0ZTNhNGM1NDkwM2IyMjU3Mjc2ZjlhOGNhNWE6NGY0ZmEzOWEwYjExNGUzYjg0MWUyZmM4MTM5NDcyM2M="}}  response:  {"msg":"Success","code":0,"ts":1610699360272,"data":{"roomName":"逛庙会上","roomUuid":"16106076001925","roleConfig":{"broadcaster":{"limit":16,"verifyType":0,"subscribe":1},"host":{"limit":1,"verifyType":0,"subscribe":1}},"roomProperties":{"board":{"state":{"grantUsers":[],"follow":0},"info":{"boardId":"062c2e2056ff11eb894d4bad573d796b","boardToken":"WHITEcGFydG5lcl9pZD1MNm5uUTJvZ2haZ1hibjdGMmc3MURVUnUycjBUY3luUVkxQzAmc2lnPTQ3ZDQwMTI3OWIyMTc0MTY4ODA0ZGY3OWY3NjIwZjNlMTgwN2ZkNTM6YWs9TDZublEyb2doWmdYYm43RjJnNzFEVVJ1MnIwVGN5blFZMUMwJmNyZWF0ZV90aW1lPTE2MTA2OTM4ODg4MjAmZXhwaXJlX3RpbWU9MTY0MjIyOTg4ODgyMCZub25jZT0xNjEwNjkzODg4ODIwMDAmcm9sZT1yb29tJnJvb21JZD0wNjJjMmUyMDU2ZmYxMWViODk0ZDRiYWQ1NzNkNzk2YiZ0ZWFtSWQ9NTQ0"}}}}}  status:  200  statusText:  
index.ts:105 16:29:25:503 AgoraEdu-SDK [DEBUG]:  login userUuid: 19teacher

**Comment by srs888001** [comment]
409代表房间已存在，不影响流程。这个是因为 我们demo没有排课系统， 所以每个人进入都要先尝试创建下 教室（防止教室不存在）。

**Comment by cwg31825** [comment]
明白
