### ISSUE TITLE
Error: window.__netlessJavaScriptLoader was override 这个的原因是啥

### ISSUE THREAD

**Issue by maoxiaoquan** [AgoraIO-Usecase/eEducation#63]
Error: window.__netlessJavaScriptLoader was override
▼ 13 stack frames were expanded.
new e
E:/project/eEducation/education_web/node_modules/_white-web-sdk@2.5.4@white-web-sdk/src/index.js:30564
push../node_modules/_white-web-sdk@2.5.4@white-web-sdk/src/index.js.lib
E:/project/eEducation/education_web/node_modules/_white-web-sdk@2.5.4@white-web-sdk/src/index.js:30539
r
E:/project/eEducation/education_web/node_modules/_white-web-sdk@2.5.4@white-web-sdk/src/index.js:13
push../node_modules/_white-web-sdk@2.5.4@white-web-sdk/src/index.js.lib
E:/project/eEducation/education_web/node_modules/_white-web-sdk@2.5.4@white-web-sdk/src/index.js:30460
r
E:/project/eEducation/education_web/node_modules/_white-web-sdk@2.5.4@white-web-sdk/src/index.js:13
push../node_modules/_white-web-sdk@2.5.4@white-web-sdk/src/index.js.lib
E:/project/eEducation/education_web/node_modules/_white-web-sdk@2.5.4@white-web-sdk/src/index.js:30333
r
E:/project/eEducation/education_web/node_modules/_white-web-sdk@2.5.4@white-web-sdk/src/index.js:13
push../node_modules/_white-web-sdk@2.5.4@white-web-sdk/src/index.js.lib
E:/project/eEducation/education_web/node_modules/_white-web-sdk@2.5.4@white-web-sdk/src/index.js:4261
r
E:/project/eEducation/education_web/node_modules/_white-web-sdk@2.5.4@white-web-sdk/src/index.js:13
push../node_modules/_white-web-sdk@2.5.4@white-web-sdk/src/index.js.lib
E:/project/eEducation/education_web/node_modules/_white-web-sdk@2.5.4@white-web-sdk/src/index.js:10007
r
E:/project/eEducation/education_web/node_modules/_white-web-sdk@2.5.4@white-web-sdk/src/index.js:13
push../node_modules/_white-web-sdk@2.5.4@white-web-sdk/src/index.js.lib
E:/project/eEducation/education_web/node_modules/_white-web-sdk@2.5.4@white-web-sdk/src/index.js:47
./node_modules/_white-web-sdk@2.5.4@white-web-sdk/src/index.js
E:/project/eEducation/education_web/node_modules/_white-web-sdk@2.5.4@white-web-sdk/src/index.js:48
▲ 13 stack frames were expanded.
__webpack_require__
E:/project/eEducation/education_web/webpack/bootstrap:785
  782 | };
  783 | 
  784 | // Execute the module function
> 785 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  786 | 
  787 | // Flag the module as loaded
  788 | module.l = true;

**Comment by maoxiaoquan** [comment]
web 项目

**Comment by plutoless** [comment]
搜索一下node_modules下，一般是因为包含了多个white-web-sdk

**Comment by plutoless** [comment]
把多余的white-web-sdk删一下
