### ISSUE TITLE
Error: cannot call it. the phase of room is not connected

### ISSUE THREAD

**Issue by cwg31825** [AgoraIO-Usecase/eEducation#64]
×
Error: cannot call it. the phase of room is not connected
▶ 2 stack frames were collapsed.
(anonymous function)
D:/Prototype2020/eEducation/education_web/src/components/mediaboard.tsx:493
  490 |     if (roomStore.state.course.lockBoard) {
  491 |       room.setViewMode(ViewMode.Broadcaster);
  492 |     } else {
> 493 |       room.setViewMode(ViewMode.Freedom);
      | ^  494 |     }
  495 |   }
  496 | }, [me.role, room]);
View compiled
▶ 18 stack frames were collapsed.
(anonymous function)
D:/Prototype2020/eEducation/modules/Router.js:33
  30 | if (!props.staticContext) {
  31 |   this.unlisten = props.history.listen(location => {
  32 |     if (this._isMounted) {
> 33 |       this.setState({ location });
     | ^  34 |     } else {
  35 |       this._pendingLocation = location;
  36 |     }
View compiled
▶ 7 stack frames were collapsed.
(anonymous function)
D:/Prototype2020/eEducation/education_web/src/pages/home.tsx:107
  104 | globalStore.showLoading();
  105 | roomStore.loginAndJoin(payload).then(() => {
  106 |   roomStore.updateSessionInfo(payload);
> 107 |   history.push(`/classroom/${path}`);
      | ^  108 | }).catch((err: any) => {
  109 |   if (err.reason) {
  110 |     globalStore.showToast({
View compiled

**Comment by plutoless** [comment]
看一下是否配置都按readme配了

**Comment by cwg31825** [comment]
刷新页面再进没问题，直播房间页面退出后在进就出这个问题

**Comment by plutoless** [comment]
console日志给下？

**Comment by cwg31825** [comment]
npm run pack:win
打包是报这个问题
./src/index.scss
Error: resolve-url-loader: CSS error
  source-map information is not available at url() declaration (found orphan CR, try removeCR option)

**Comment by cwg31825** [comment]
`uid 296914
index.js:7 RTM:INFO A channel created, id 0202cb962ac59075b964b07152d234b70. +16s
index.js:7 RTM:INFO The channel 0202cb962ac59075b964b07152d234b70 joined successfully. +58ms
room.ts:599 >>>>>>>>>>#room:  1
room.ts:709 users {uid: "296914", rid: "0202cb962ac59075b964b07152d234b70", role: "teacher", roomName: "123", roomType: 0, …}
room.ts:730 teacher attrs: >>>>  {uid: "296914", account: "567", chat: 1, video: 1, audio: 1, …}
agora-rtm-client.ts:163 [rtm-client] updateChannelAttrsByKey  {uid: "296914", account: "567", chat: 1, video: 1, audio: 1, …}  key  teacher {teacher: "{"uid":"296914","account":"567","chat":1,"video":1…":1,"mute_chat":0,"class_state":0,"lock_board":0}"}
index.js:7 RTM:INFO Channel MemberJoined - 0202cb962ac59075b964b07152d234b70, memberId: 296914. +3ms
mediaboard.tsx:414 [mediaboard] uploadPhase:    convertPhase:  
index.js:8 Uncaught Error: cannot call it. the phase of room is not connected
    at t.assertRoomIsConnected (index.js:8)
    at t.setViewMode (index.js:8)`

**Comment by cwg31825** [comment]
index.js:8 Uncaught Error: cannot call it. the phase of room is not connected
    at t.assertRoomIsConnected (index.js:8)
    at t.setViewMode (index.js:8)
    at mediaboard.tsx:493
    at commitHookEffectList (react-dom.development.js:22030)
    at commitPassiveHookEffects (react-dom.development.js:22064)
    at HTMLUnknownElement.callCallback (react-dom.development.js:336)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:385)
    at invokeGuardedCallback (react-dom.development.js:440)
    at flushPassiveEffectsImpl (react-dom.development.js:25392)
    at unstable_runWithPriority (scheduler.development.js:697)
    at runWithPriority$2 (react-dom.development.js:12149)
    at flushPassiveEffects (react-dom.development.js:25361)
    at performSyncWorkOnRoot (react-dom.development.js:24251)
    at react-dom.development.js:12199
    at unstable_runWithPriority (scheduler.development.js:697)
    at runWithPriority$2 (react-dom.development.js:12149)
    at flushSyncCallbackQueueImpl (react-dom.development.js:12194)
    at flushSyncCallbackQueue (react-dom.development.js:12182)
    at scheduleUpdateOnFiber (react-dom.development.js:23709)
    at Object.enqueueSetState (react-dom.development.js:13994)
    at Router.push../node_modules/react/cjs/react.development.js.Component.setState (react.development.js:325)
    at Router.js:33
    at listener (history.js:155)
    at history.js:173
    at Array.forEach (<anonymous>)
    at Object.notifyListeners (history.js:172)
    at setState (history.js:561)
    at history.js:664
    at Object.confirmTransitionTo (history.js:145)
    at Object.push (history.js:648)
    at home.tsx:107
t.assertRoomIsConnected @ index.js:8
t.setViewMode @ index.js:8
(anonymous) @ mediaboard.tsx:493
commitHookEffectList @ react-dom.development.js:22030
commitPassiveHookEffects @ react-dom.development.js:22064
callCallback @ react-dom.development.js:336
invokeGuardedCallbackDev @ react-dom.development.js:385
invokeGuardedCallback @ react-dom.development.js:440
flushPassiveEffectsImpl @ react-dom.development.js:25392
unstable_runWithPriority @ scheduler.development.js:697
runWithPriority$2 @ react-dom.development.js:12149
flushPassiveEffects @ react-dom.development.js:25361
performSyncWorkOnRoot @ react-dom.development.js:24251
(anonymous) @ react-dom.development.js:12199
unstable_runWithPriority @ scheduler.development.js:697
runWithPriority$2 @ react-dom.development.js:12149
flushSyncCallbackQueueImpl @ react-dom.development.js:12194
flushSyncCallbackQueue @ react-dom.development.js:12182
scheduleUpdateOnFiber @ react-dom.development.js:23709
enqueueSetState @ react-dom.development.js:13994
push../node_modules/react/cjs/react.development.js.Component.setState @ react.development.js:325
(anonymous) @ Router.js:33
listener @ history.js:155
(anonymous) @ history.js:173
notifyListeners @ history.js:172
setState @ history.js:561
(anonymous) @ history.js:664
confirmTransitionTo @ history.js:145
push @ history.js:648
(anonymous) @ home.tsx:107
Promise.then (async)
handleSubmit @ home.tsx:105
callCallback @ react-dom.development.js:336
invokeGuardedCallbackDev @ react-dom.development.js:385
invokeGuardedCallback @ react-dom.development.js:440
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:454
executeDispatch @ react-dom.development.js:584
executeDispatchesInOrder @ react-dom.development.js:609
executeDispatchesAndRelease @ react-dom.development.js:713
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:722
forEachAccumulated @ react-dom.development.js:694
runEventsInBatch @ react-dom.development.js:739
runExtractedPluginEventsInBatch @ react-dom.development.js:880
handleTopLevel @ react-dom.development.js:5803
batchedEventUpdates$1 @ react-dom.development.js:24401
batchedEventUpdates @ react-dom.development.js:1415
dispatchEventForPluginEventSystem @ react-dom.development.js:5894
attemptToDispatchEvent @ react-dom.development.js:6010
dispatchEvent @ react-dom.development.js:5914
unstable_runWithPriority @ scheduler.development.js:697
runWithPriority$2 @ react-dom.development.js:12149
discreteUpdates$1 @ react-dom.development.js:24417
discreteUpdates @ react-dom.development.js:1438
dispatchDiscreteEvent @ react-dom.development.js:5881
index.tsx:99 [route] prevRoute:  /classroom/one-to-one
index.tsx:216 [agora-rtc] add event listener
index.tsx:319 [agora-web] remove event listener
index.js:1 The above error occurred in the <MediaBoard> component:
    in MediaBoard (at one-to-one.tsx:20)
    in div (at one-to-one.tsx:19)
    in OneToOne (at pages/index.tsx:35)
    in div (at classroom/index.tsx:408)
    in RoomPage (at pages/index.tsx:34)
    in Route (at pages/index.tsx:33)
    in RootProvider (at pages/index.tsx:24)
    in PlatformContainer (at pages/index.tsx:23)
    in Route (at custom-browser-router.tsx:9)
    in Router (created by HashRouter)
    in HashRouter (at custom-browser-router.tsx:8)
    in CustomBrowserRouter (at pages/index.tsx:22)
    in ThemeProvider (at theme-container.tsx:51)
    in Unknown (at pages/index.tsx:21)
    in Unknown (at src/index.tsx:8)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

**Comment by cwg31825** [comment]
![aaa](https://user-images.githubusercontent.com/25262280/74016509-819e9b00-49cd-11ea-9618-3546a61e2a50.png)

**Comment by Matrixbirds** [comment]
@cwg31825  看上去是白板状态没有重置 可以拉一下最新的master分支或者 [参考这里](https://github.com/AgoraIO-Usecase/eEducation/commit/92fe1c0db4d32518f8db6e44ffce3851255e0010)修改一下

**Comment by cwg31825** [comment]
> @ cwg31825 看起来是白板状态没有重置可以拉一下最新的主副本或者[参考这里](https://github.com/AgoraIO-Usecase/eEducation/commit/92fe1c0db4d32518f8db6e44ffce3851255e0010)修改一下

谢谢
