### ISSUE TITLE
Document  上传功能

### ISSUE THREAD

**Issue by zy0228** [AgoraIO-Usecase/eEducation#69]
document 上传功能有做吗？ 我想接这个功能怎么接

**Comment by plutoless** [comment]
你好 有做的，把对应的OSS配置和netless后台相关的权限打开就可以了。

**Comment by zy0228** [comment]
很感谢你，我已经可以做到上传了，请问学生端如何拿到教师上传的的文件





------------------ 原始邮件 ------------------
发件人: Qianze Zhang <notifications@github.com&gt;
发送时间: 2020年2月14日 12:37
收件人: AgoraIO-Usecase/eEducation <eEducation@noreply.github.com&gt;
抄送: Snoop Zhang <2472305432@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[AgoraIO-Usecase/eEducation] Document  上传功能 (#69)




你好 有做的，把对应的OSS配置和netless后台相关的权限打开就可以了。

**Comment by plutoless** [comment]
你说文档吗？

**Comment by plutoless** [comment]
上传后就可以在左边工具栏里打开和学生同步一起看了
