### ISSUE TITLE
safari或者一些低一点版本的chrome浏览器，聊天室的对话超过一屏显示会压缩

### ISSUE THREAD

**Issue by Easyzhou** [AgoraIO-Usecase/eEducation#75]
safari或者一些低一点版本的chrome浏览器，聊天室的对话超过一屏显示会压缩，所有对话会重叠在一起，可以在布局中加入flex-shrink:0;解决这个问题

**Comment by Matrixbirds** [comment]
感谢贡献 之前没有覆盖到这些浏览器 会加到最近发布一个新版本。

**Comment by Matrixbirds** [comment]
最新版本已按照您的指导修复了该问题。可以用最新的代码了
