### ISSUE TITLE
学生听不到老师电脑扬声器的声音

### ISSUE THREAD

**Issue by chenny2020** [AgoraIO-Usecase/eEducation#79]
老师在播放视频课件的时候，学生只能看到画面，听不到视频课件的声音，只能听到老师讲话的声音（麦克风的声音），扬声器的声音没有

**Comment by Matrixbirds** [comment]
是大班课场景里吗 学生没有开音视频 看老师播放的课件？

**Comment by chenny2020** [comment]
是大班课，学生开了音视频，学生只能看到画面和老师麦克风讲话声音，听不到视频课件的声音，视频课件的声音是电脑扬声器播放出来的

**Comment by chenny2020** [comment]
产品不是有个设置功能吗，可以设置声音来源为“扬声器”吗

**Comment by Matrixbirds** [comment]
那个功能目前只能用于媒体（音视频）课件暂时还不行，课件应该会有提示让你解开禁言 因为这里播放音频或者视频是会有浏览器autoplay限制的 为了能播放所以默认禁言播放了
