### ISSUE TITLE
PDF file uploaded but not show in in white board

### ISSUE THREAD

**Issue by Nondukishor** [AgoraIO-Usecase/eEducation#8]
Showing this message

index.ts:71 Error: failed to convert "http://opdemy.oss-ap-south-1.aliyuncs.com/opdemylive/dc269950cf4d11ea9f09772fdf72e688.pdf" with status 403
    at e.<anonymous> (index.js:8)
    at index.js:8
    at Object.next (index.js:8)
    at a (index.js:8)
(anonymous) @ index.ts:71

**Comment by Matrixbirds** [comment]
It seems you need enable converting service in https://netless.link dashboard center.
