### ISSUE TITLE
can't use audio input if device not have a webcam

### ISSUE THREAD

**Issue by ecavalier** [AgoraIO-Usecase/eEducation#9]
If the device doesn't have a webcam, the audio not working

'index.ts:71 23:16:31:313 Agora-SDK [ERROR]: Failed to GetUserMedia NotFoundError 8 Requested device not found DOMException: Requested device not found
(anonymous) @ index.ts:71
e @ 2.00d93f4d.chunk.js:131533
p @ 2.00d93f4d.chunk.js:131484
l @ 2.00d93f4d.chunk.js:136286
Promise.catch (async)
d @ 2.00d93f4d.chunk.js:136295
pe @ 2.00d93f4d.chunk.js:136378
t.init @ 2.00d93f4d.chunk.js:137903
(anonymous) @ agora-rtc-client.ts:312
(anonymous) @ agora-rtc-client.ts:311
c @ 2.00d93f4d.chunk.js:304631
(anonymous) @ 2.00d93f4d.chunk.js:304848
(anonymous) @ 2.00d93f4d.chunk.js:304684
r @ 2.00d93f4d.chunk.js:129
s @ 2.00d93f4d.chunk.js:151
(anonymous) @ 2.00d93f4d.chunk.js:158
(anonymous) @ 2.00d93f4d.chunk.js:147
(anonymous) @ agora-rtc-client.ts:51
(anonymous) @ agora-web-client.ts:127
c @ 2.00d93f4d.chunk.js:304631
(anonymous) @ 2.00d93f4d.chunk.js:304848
(anonymous) @ 2.00d93f4d.chunk.js:304684
r @ 2.00d93f4d.chunk.js:129
s @ 2.00d93f4d.chunk.js:151
(anonymous) @ 2.00d93f4d.chunk.js:158
(anonymous) @ 2.00d93f4d.chunk.js:147
(anonymous) @ agora-web-client.ts:83
(anonymous) @ use-setting-control.tsx:55
c @ 2.00d93f4d.chunk.js:304631
(anonymous) @ 2.00d93f4d.chunk.js:304848
(anonymous) @ 2.00d93f4d.chunk.js:304684
r @ 2.00d93f4d.chunk.js:129
s @ 2.00d93f4d.chunk.js:151
(anonymous) @ 2.00d93f4d.chunk.js:158
(anonymous) @ 2.00d93f4d.chunk.js:147
(anonymous) @ use-setting-control.tsx:54
(anonymous) @ use-setting-control.tsx:63
os @ 2.00d93f4d.chunk.js:301704
_u @ 2.00d93f4d.chunk.js:303056
t.unstable_runWithPriority @ 2.00d93f4d.chunk.js:304276
zi @ 2.00d93f4d.chunk.js:299378
mu @ 2.00d93f4d.chunk.js:303036
eu @ 2.00d93f4d.chunk.js:302432
(anonymous) @ 2.00d93f4d.chunk.js:299413
t.unstable_runWithPriority @ 2.00d93f4d.chunk.js:304276
zi @ 2.00d93f4d.chunk.js:299378
Hi @ 2.00d93f4d.chunk.js:299408
Wi @ 2.00d93f4d.chunk.js:299398
R @ 2.00d93f4d.chunk.js:303827
Kt @ 2.00d93f4d.chunk.js:297891
Show 19 more frames from Library code
index.ts:71 23:16:31:316 Agora-SDK [ERROR]: [undefined]  Media access NotFoundError: Requested device not found. 8

**Comment by plutoless** [comment]
we will release a new version in early October which will fix this issue.

**Comment by ecavalier** [comment]
any hint to fix it by myself?
thanks in advance

**Comment by plutoless** [comment]
when creating local stream, currently we will pass {video: true, audio: true}, which will fail if either of the video/audio stream fail to create. You will need to create video stream and audio stream separately, and then use addTrack/removeTrack to combine the tracks of two stream into one.
